before_script:
  - apt-get update -qy
  - apt-get install -y build-essential
  - apt-get install -y cmake
  - apt-get install -y clang
  - apt-get install -y libsdl2-ttf-dev
  - apt-get install -y libdevil-dev

stages:
  - build

build:
  stage: build
  script:
    - mkdir build && cd build
    - cmake ..
    - cmake --build .
