#ifndef DOLORI_NETWORK_PACKETS_H_
#define DOLORI_NETWORK_PACKETS_H_

#include "Common/character_info.h"

#define PACKETVER 20080910
#define MAP_NAME_LENGTH (11 + 1)
#define MAP_NAME_LENGTH_EXT (MAP_NAME_LENGTH + 4)

enum {
  HEADER_CA_LOGIN = 0x64,
  HEADER_CH_ENTER = 0x65,
  HEADER_CH_SELECT_CHAR = 0x66,
  HEADER_CH_MAKE_CHAR = 0x67,
  HEADER_CH_DELETE_CHAR = 0x68,
  HEADER_AC_ACCEPT_LOGIN = 0x69,
  HEADER_AC_REFUSE_LOGIN = 0x6a,
  HEADER_HC_ACCEPT_ENTER = 0x6b,
  HEADER_HC_REFUSE_ENTER = 0x6c,
  HEADER_HC_ACCEPT_MAKECHAR = 0x6d,
  HEADER_HC_REFUSE_MAKECHAR = 0x6e,
  HEADER_HC_ACCEPT_DELETECHAR = 0x6f,
  HEADER_HC_REFUSE_DELETECHAR = 0x70,
  HEADER_HC_NOTIFY_ZONESVR = 0x71,
  HEADER_CZ_ENTER = 0x72,
  HEADER_ZC_ACCEPT_ENTER = 0x73,
  HEADER_ZC_REFUSE_ENTER = 0x74,
  HEADER_ZC_NOTIFY_INITCHAR = 0x75,
  HEADER_ZC_NOTIFY_UPDATECHAR = 0x76,
  HEADER_ZC_NOTIFY_UPDATEPLAYER = 0x77,
  HEADER_ZC_NOTIFY_STANDENTRY = 0x78,
  HEADER_ZC_NOTIFY_NEWENTRY = 0x79,
  HEADER_ZC_NOTIFY_ACTENTRY = 0x7a,
  HEADER_ZC_NOTIFY_MOVEENTRY = 0x7b,
  HEADER_ZC_NOTIFY_STANDENTRY_NPC = 0x7c,
  HEADER_CZ_NOTIFY_ACTORINIT = 0x7d,
  HEADER_CZ_REQUEST_TIME = 0x7e,
  HEADER_ZC_NOTIFY_TIME = 0x7f,
  HEADER_ZC_NOTIFY_VANISH = 0x80,
  HEADER_SC_NOTIFY_BAN = 0x81,
  HEADER_CZ_REQUEST_QUIT = 0x82,
  HEADER_ZC_ACCEPT_QUIT = 0x83,
  HEADER_ZC_REFUSE_QUIT = 0x84,
  HEADER_CZ_REQUEST_MOVE = 0x85,
  HEADER_ZC_NOTIFY_MOVE = 0x86,
  HEADER_ZC_NOTIFY_PLAYERMOVE = 0x87,
  HEADER_ZC_STOPMOVE = 0x88,
  HEADER_CZ_REQUEST_ACT = 0x89,
  HEADER_ZC_NOTIFY_ACT = 0x8a,
  HEADER_ZC_NOTIFY_ACT_POSITION = 0x8b,
#if PACKETVER >= 20050110
  HEADER_CZ_REQUEST_CHAT = 0xf3,
#elif PACKETVER >= 20041129
  HEADER_CZ_REQUEST_CHAT = 0x85,
#elif PACKETVER >= 20040906
  HEADER_CZ_REQUEST_CHAT = 0x9f,
#elif PACKETVER >= 20040726
  HEADER_CZ_REQUEST_CHAT = 0xf3,
#else
  HEADER_CZ_REQUEST_CHAT = 0x8c,
#endif
  HEADER_ZC_NOTIFY_CHAT = 0x8d,
  HEADER_ZC_NOTIFY_PLAYERCHAT = 0x8e,
  HEADER_SERVER_ENTRY_ACK = 0x8f,
  HEADER_CZ_CONTACTNPC = 0x90,
  HEADER_ZC_NPCACK_MAPMOVE = 0x91,
  HEADER_ZC_NPCACK_SERVERMOVE = 0x92,
  HEADER_ZC_NPCACK_ENABLE = 0x93,
  HEADER_CZ_REQNAME = 0x94,
  HEADER_ZC_ACK_REQNAME = 0x95,
  HEADER_CZ_WHISPER = 0x96,
  HEADER_ZC_WHISPER = 0x97,
  HEADER_ZC_ACK_WHISPER = 0x98,
  HEADER_CZ_BROADCAST = 0x99,
  HEADER_ZC_BROADCAST = 0x9a,
  HEADER_CZ_CHANGE_DIRECTION = 0x9b,
  HEADER_ZC_CHANGE_DIRECTION = 0x9c,
  HEADER_ZC_ITEM_ENTRY = 0x9d,
  HEADER_ZC_ITEM_FALL_ENTRY = 0x9e,
  HEADER_CZ_ITEM_PICKUP = 0x9f,
  HEADER_ZC_ITEM_PICKUP_ACK = 0xa0,
  HEADER_ZC_ITEM_DISAPPEAR = 0xa1,
  HEADER_CZ_ITEM_THROW = 0xa2,
  HEADER_ZC_NORMAL_ITEMLIST = 0xa3,
  HEADER_ZC_EQUIPMENT_ITEMLIST = 0xa4,
  HEADER_ZC_STORE_NORMAL_ITEMLIST = 0xa5,
  HEADER_ZC_STORE_EQUIPMENT_ITEMLIST = 0xa6,
#if PACKETVER >= 20080910
  HEADER_CZ_USE_ITEM = 0x439,
#elif PACKETVER >= 20050110
  HEADER_CZ_USE_ITEM = 0x9f,
#else
  HEADER_CZ_USE_ITEM = 0xa7,
#endif
  HEADER_ZC_USE_ITEM_ACK = 0xa8,
  HEADER_CZ_REQ_WEAR_EQUIP = 0xa9,
  HEADER_ZC_REQ_WEAR_EQUIP_ACK = 0xaa,
  HEADER_CZ_REQ_TAKEOFF_EQUIP = 0xab,
  HEADER_ZC_REQ_TAKEOFF_EQUIP_ACK = 0xac,
  HEADER_CZ_REQ_ITEM_EXPLANATION_BYNAME = 0xad,
  HEADER_ZC_REQ_ITEM_EXPLANATION_ACK = 0xae,
  HEADER_ZC_ITEM_THROW_ACK = 0xaf,
  HEADER_ZC_PAR_CHANGE = 0xb0,
  HEADER_ZC_LONGPAR_CHANGE = 0xb1,
  HEADER_CZ_RESTART = 0xb2,
  HEADER_ZC_RESTART_ACK = 0xb3,
  HEADER_ZC_SAY_DIALOG = 0xb4,
  HEADER_ZC_WAIT_DIALOG = 0xb5,
  HEADER_ZC_CLOSE_DIALOG = 0xb6,
  HEADER_ZC_MENU_LIST = 0xb7,
  HEADER_CZ_CHOOSE_MENU = 0xb8,
  HEADER_CZ_REQ_NEXT_SCRIPT = 0xb9,
  HEADER_CZ_REQ_STATUS = 0xba,
  HEADER_CZ_STATUS_CHANGE = 0xbb,
  HEADER_ZC_STATUS_CHANGE_ACK = 0xbc,
  HEADER_ZC_STATUS = 0xbd,
  HEADER_ZC_STATUS_CHANGE = 0xbe,
  HEADER_CZ_REQ_EMOTION = 0xbf,
  HEADER_ZC_EMOTION = 0xc0,
  HEADER_CZ_REQ_USER_COUNT = 0xc1,
  HEADER_ZC_USER_COUNT = 0xc2,
  HEADER_ZC_SPRITE_CHANGE = 0xc3,
  HEADER_ZC_SELECT_DEALTYPE = 0xc4,
  HEADER_CZ_ACK_SELECT_DEALTYPE = 0xc5,
  HEADER_ZC_PC_PURCHASE_ITEMLIST = 0xc6,
  HEADER_ZC_PC_SELL_ITEMLIST = 0xc7,
  HEADER_CZ_PC_PURCHASE_ITEMLIST = 0xc8,
  HEADER_CZ_PC_SELL_ITEMLIST = 0xc9,
  HEADER_ZC_PC_PURCHASE_RESULT = 0xca,
  HEADER_ZC_PC_SELL_RESULT = 0xcb,
  HEADER_CZ_DISCONNECT_CHARACTER = 0xcc,
  HEADER_ZC_ACK_DISCONNECT_CHARACTER = 0xcd,
  HEADER_CZ_DISCONNECT_ALL_CHARACTER = 0xce,
  HEADER_CZ_SETTING_WHISPER_PC = 0xcf,
  HEADER_CZ_SETTING_WHISPER_STATE = 0xd0,
  HEADER_ZC_SETTING_WHISPER_PC = 0xd1,
  HEADER_ZC_SETTING_WHISPER_STATE = 0xd2,
  HEADER_CZ_REQ_WHISPER_LIST = 0xd3,
  HEADER_ZC_WHISPER_LIST = 0xd4,
  HEADER_CZ_CREATE_CHATROOM = 0xd5,
  HEADER_ZC_ACK_CREATE_CHATROOM = 0xd6,
  HEADER_ZC_ROOM_NEWENTRY = 0xd7,
  HEADER_ZC_DESTROY_ROOM = 0xd8,
  HEADER_CZ_REQ_ENTER_ROOM = 0xd9,
  HEADER_ZC_REFUSE_ENTER_ROOM = 0xda,
  HEADER_ZC_ENTER_ROOM = 0xdb,
  HEADER_ZC_MEMBER_NEWENTRY = 0xdc,
  HEADER_ZC_MEMBER_EXIT = 0xdd,
  HEADER_CZ_CHANGE_CHATROOM = 0xde,
  HEADER_ZC_CHANGE_CHATROOM = 0xdf,
  HEADER_CZ_REQ_ROLE_CHANGE = 0xe0,
  HEADER_ZC_ROLE_CHANGE = 0xe1,
  HEADER_CZ_REQ_EXPEL_MEMBER = 0xe2,
  HEADER_CZ_EXIT_ROOM = 0xe3,
  HEADER_CZ_REQ_EXCHANGE_ITEM = 0xe4,
  HEADER_ZC_REQ_EXCHANGE_ITEM = 0xe5,
  HEADER_CZ_ACK_EXCHANGE_ITEM = 0xe6,
  HEADER_ZC_ACK_EXCHANGE_ITEM = 0xe7,
  HEADER_CZ_ADD_EXCHANGE_ITEM = 0xe8,
  HEADER_ZC_ADD_EXCHANGE_ITEM = 0xe9,
  HEADER_ZC_ACK_ADD_EXCHANGE_ITEM = 0xea,
  HEADER_CZ_CONCLUDE_EXCHANGE_ITEM = 0xeb,
  HEADER_ZC_CONCLUDE_EXCHANGE_ITEM = 0xec,
  HEADER_CZ_CANCEL_EXCHANGE_ITEM = 0xed,
  HEADER_ZC_CANCEL_EXCHANGE_ITEM = 0xee,
  HEADER_CZ_EXEC_EXCHANGE_ITEM = 0xef,
  HEADER_ZC_EXEC_EXCHANGE_ITEM = 0xf0,
  HEADER_ZC_EXCHANGEITEM_UNDO = 0xf1,
  HEADER_ZC_NOTIFY_STOREITEM_COUNTINFO = 0xf2,
  HEADER_CZ_MOVE_ITEM_FROM_BODY_TO_STORE = 0xf3,
  HEADER_ZC_ADD_ITEM_TO_STORE = 0xf4,
  HEADER_CZ_MOVE_ITEM_FROM_STORE_TO_BODY = 0xf5,
  HEADER_ZC_DELETE_ITEM_FROM_STORE = 0xf6,
  HEADER_CZ_CLOSE_STORE = 0xf7,
  HEADER_ZC_CLOSE_STORE = 0xf8,
  HEADER_CZ_MAKE_GROUP = 0xf9,
  HEADER_ZC_ACK_MAKE_GROUP = 0xfa,
  HEADER_ZC_GROUP_LIST = 0xfb,
  HEADER_CZ_REQ_JOIN_GROUP = 0xfc,
  HEADER_ZC_ACK_REQ_JOIN_GROUP = 0xfd,
  HEADER_ZC_REQ_JOIN_GROUP = 0xfe,
  HEADER_CZ_JOIN_GROUP = 0xff,
  HEADER_CZ_REQ_LEAVE_GROUP = 0x100,
  HEADER_ZC_GROUPINFO_CHANGE = 0x101,
  HEADER_CZ_CHANGE_GROUPEXPOPTION = 0x102,
  HEADER_CZ_REQ_EXPEL_GROUP_MEMBER = 0x103,
  HEADER_ZC_ADD_MEMBER_TO_GROUP = 0x104,
  HEADER_ZC_DELETE_MEMBER_FROM_GROUP = 0x105,
  HEADER_ZC_NOTIFY_HP_TO_GROUPM = 0x106,
  HEADER_ZC_NOTIFY_POSITION_TO_GROUPM = 0x107,
  HEADER_CZ_REQUEST_CHAT_PARTY = 0x108,
  HEADER_ZC_NOTIFY_CHAT_PARTY = 0x109,
  HEADER_ZC_MVP_GETTING_ITEM = 0x10a,
  HEADER_ZC_MVP_GETTING_SPECIAL_EXP = 0x10b,
  HEADER_ZC_MVP = 0x10c,
  HEADER_ZC_THROW_MVPITEM = 0x10d,
  HEADER_ZC_SKILLINFO_UPDATE = 0x10e,
  HEADER_ZC_SKILLINFO_LIST = 0x10f,
  HEADER_ZC_ACK_TOUSESKILL = 0x110,
  HEADER_ZC_ADD_SKILL = 0x111,
  HEADER_CZ_UPGRADE_SKILLLEVEL = 0x112,
  HEADER_CZ_USE_SKILL = 0x113,
  HEADER_ZC_NOTIFY_SKILL = 0x114,
  HEADER_ZC_NOTIFY_SKILL_POSITION = 0x115,
  HEADER_CZ_USE_SKILL_TOGROUND = 0x116,
  HEADER_ZC_NOTIFY_GROUNDSKILL = 0x117,
  HEADER_CZ_CANCEL_LOCKON = 0x118,
  HEADER_ZC_STATE_CHANGE = 0x119,
  HEADER_ZC_USE_SKILL = 0x11a,
  HEADER_CZ_SELECT_WARPPOINT = 0x11b,
  HEADER_ZC_WARPLIST = 0x11c,
  HEADER_CZ_REMEMBER_WARPPOINT = 0x11d,
  HEADER_ZC_ACK_REMEMBER_WARPPOINT = 0x11e,
  HEADER_ZC_SKILL_ENTRY = 0x11f,
  HEADER_ZC_SKILL_DISAPPEAR = 0x120,
  HEADER_ZC_NOTIFY_CARTITEM_COUNTINFO = 0x121,
  HEADER_ZC_CART_EQUIPMENT_ITEMLIST = 0x122,
  HEADER_ZC_CART_NORMAL_ITEMLIST = 0x123,
  HEADER_ZC_ADD_ITEM_TO_CART = 0x124,
  HEADER_ZC_DELETE_ITEM_FROM_CART = 0x125,
  HEADER_CZ_MOVE_ITEM_FROM_BODY_TO_CART = 0x126,
  HEADER_CZ_MOVE_ITEM_FROM_CART_TO_BODY = 0x127,
  HEADER_CZ_MOVE_ITEM_FROM_STORE_TO_CART = 0x128,
  HEADER_CZ_MOVE_ITEM_FROM_CART_TO_STORE = 0x129,
  HEADER_CZ_REQ_CARTOFF = 0x12a,
  HEADER_ZC_CARTOFF = 0x12b,
  HEADER_ZC_ACK_ADDITEM_TO_CART = 0x12c,
  HEADER_ZC_OPENSTORE = 0x12d,
  HEADER_CZ_REQ_CLOSESTORE = 0x12e,
  HEADER_CZ_REQ_OPENSTORE = 0x12f,
  HEADER_CZ_REQ_BUY_FROMMC = 0x130,
  HEADER_ZC_STORE_ENTRY = 0x131,
  HEADER_ZC_DISAPPEAR_ENTRY = 0x132,
  HEADER_ZC_PC_PURCHASE_ITEMLIST_FROMMC = 0x133,
  HEADER_CZ_PC_PURCHASE_ITEMLIST_FROMMC = 0x134,
  HEADER_ZC_PC_PURCHASE_RESULT_FROMMC = 0x135,
  HEADER_ZC_PC_PURCHASE_MYITEMLIST = 0x136,
  HEADER_ZC_DELETEITEM_FROM_MCSTORE = 0x137,
  HEADER_CZ_PKMODE_CHANGE = 0x138,
  HEADER_ZC_ATTACK_FAILURE_FOR_DISTANCE = 0x139,
  HEADER_ZC_ATTACK_RANGE = 0x13a,
  HEADER_ZC_ACTION_FAILURE = 0x13b,
  HEADER_ZC_EQUIP_ARROW = 0x13c,
  HEADER_ZC_RECOVERY = 0x13d,
  HEADER_ZC_USESKILL_ACK = 0x13e,
  HEADER_CZ_ITEM_CREATE = 0x13f,
  HEADER_CZ_MOVETO_MAP = 0x140,
  HEADER_ZC_COUPLESTATUS = 0x141,
  HEADER_ZC_OPEN_EDITDLG = 0x142,
  HEADER_CZ_INPUT_EDITDLG = 0x143,
  HEADER_ZC_COMPASS = 0x144,
  HEADER_ZC_SHOW_IMAGE = 0x145,
  HEADER_CZ_CLOSE_DIALOG = 0x146,
  HEADER_ZC_AUTORUN_SKILL = 0x147,
  HEADER_ZC_RESURRECTION = 0x148,
  HEADER_CZ_REQ_GIVE_MANNER_POINT = 0x149,
  HEADER_ZC_ACK_GIVE_MANNER_POINT = 0x14a,
  HEADER_ZC_NOTIFY_MANNER_POINT_GIVEN = 0x14b,
  HEADER_ZC_MYGUILD_BASIC_INFO = 0x14c,
  HEADER_CZ_REQ_GUILD_MENUINTERFACE = 0x14d,
  HEADER_ZC_ACK_GUILD_MENUINTERFACE = 0x14e,
  HEADER_CZ_REQ_GUILD_MENU = 0x14f,
  HEADER_ZC_GUILD_INFO = 0x150,
  HEADER_CZ_REQ_GUILD_EMBLEM_IMG = 0x151,
  HEADER_ZC_GUILD_EMBLEM_IMG = 0x152,
  HEADER_CZ_REGISTER_GUILD_EMBLEM_IMG = 0x153,
  HEADER_ZC_MEMBERMGR_INFO = 0x154,
  HEADER_CZ_REQ_CHANGE_MEMBERPOS = 0x155,
  HEADER_ZC_ACK_REQ_CHANGE_MEMBERS = 0x156,
  HEADER_CZ_REQ_OPEN_MEMBER_INFO = 0x157,
  XXXXX_HEADER_ZC_ACK_OPEN_MEMBER_INFO = 0x158,
  HEADER_CZ_REQ_LEAVE_GUILD = 0x159,
  HEADER_ZC_ACK_LEAVE_GUILD = 0x15a,
  HEADER_CZ_REQ_BAN_GUILD = 0x15b,
  HEADER_ZC_ACK_BAN_GUILD = 0x15c,
  HEADER_CZ_REQ_DISORGANIZE_GUILD = 0x15d,
  HEADER_ZC_ACK_DISORGANIZE_GUILD_RESULT = 0x15e,
  HEADER_ZC_ACK_DISORGANIZE_GUILD = 0x15f,
  HEADER_ZC_POSITION_INFO = 0x160,
  HEADER_CZ_REG_CHANGE_GUILD_POSITIONINFO = 0x161,
  HEADER_ZC_GUILD_SKILLINFO = 0x162,
  HEADER_ZC_BAN_LIST = 0x163,
  HEADER_ZC_OTHER_GUILD_LIST = 0x164,
  HEADER_CZ_REQ_MAKE_GUILD = 0x165,
  HEADER_ZC_POSITION_ID_NAME_INFO = 0x166,
  HEADER_ZC_RESULT_MAKE_GUILD = 0x167,
  HEADER_CZ_REQ_JOIN_GUILD = 0x168,
  HEADER_ZC_ACK_REQ_JOIN_GUILD = 0x169,
  HEADER_ZC_REQ_JOIN_GUILD = 0x16a,
  HEADER_CZ_JOIN_GUILD = 0x16b,
  HEADER_ZC_UPDATE_GDID = 0x16c,
  HEADER_ZC_UPDATE_CHARSTAT = 0x16d,
  HEADER_CZ_GUILD_NOTICE = 0x16e,
  HEADER_ZC_GUILD_NOTICE = 0x16f,
  HEADER_CZ_REQ_ALLY_GUILD = 0x170,
  HEADER_ZC_REQ_ALLY_GUILD = 0x171,
  HEADER_CZ_ALLY_GUILD = 0x172,
  HEADER_ZC_ACK_REQ_ALLY_GUILD = 0x173,
  HEADER_ZC_ACK_CHANGE_GUILD_POSITIONINFO = 0x174,
  HEADER_CZ_REQ_GUILD_MEMBER_INFO = 0x175,
  HEADER_ZC_ACK_GUILD_MEMBER_INFO = 0x176,
  HEADER_ZC_ITEMIDENTIFY_LIST = 0x177,
  HEADER_CZ_REQ_ITEMIDENTIFY = 0x178,
  HEADER_ZC_ACK_ITEMIDENTIFY = 0x179,
  HEADER_CZ_REQ_ITEMCOMPOSITION_LIST = 0x17a,
  HEADER_ZC_ITEMCOMPOSITION_LIST = 0x17b,
  HEADER_CZ_REQ_ITEMCOMPOSITION = 0x17c,
  HEADER_ZC_ACK_ITEMCOMPOSITION = 0x17d,
  HEADER_CZ_GUILD_CHAT = 0x17e,
  HEADER_ZC_GUILD_CHAT = 0x17f,
  HEADER_CZ_REQ_HOSTILE_GUILD = 0x180,
  HEADER_ZC_ACK_REQ_HOSTILE_GUILD = 0x181,
  HEADER_ZC_MEMBER_ADD = 0x182,
  HEADER_CZ_REQ_DELETE_RELATED_GUILD = 0x183,
  HEADER_ZC_DELETE_RELATED_GUILD = 0x184,
  HEADER_ZC_ADD_RELATED_GUILD = 0x185,
  HEADER_COLLECTORDEAD = 0x186,
  HEADER_PING = 0x187,
  HEADER_ZC_ACK_ITEMREFINING = 0x188,
  HEADER_ZC_NOTIFY_MAPINFO = 0x189,
  HEADER_CZ_REQ_DISCONNECT = 0x18a,
  HEADER_ZC_ACK_REQ_DISCONNECT = 0x18b,
  HEADER_ZC_MONSTER_INFO = 0x18c,
  HEADER_ZC_MAKABLEITEMLIST = 0x18d,
  HEADER_CZ_REQMAKINGITEM = 0x18e,
  HEADER_ZC_ACK_REQMAKINGITEM = 0x18f,
  HEADER_CZ_USE_SKILL_TOGROUND_WITHTALKBOX = 0x190,
  HEADER_ZC_TALKBOX_CHATCONTENTS = 0x191,
  HEADER_ZC_UPDATE_MAPINFO = 0x192,
  HEADER_CZ_REQNAME_BYGID = 0x193,
  HEADER_ZC_ACK_REQNAME_BYGID = 0x194,
  HEADER_ZC_ACK_REQNAMEALL = 0x195,
  HEADER_ZC_MSG_STATE_CHANGE = 0x196,
  HEADER_CZ_RESET = 0x197,
  HEADER_CZ_CHANGE_MAPTYPE = 0x198,
  HEADER_ZC_NOTIFY_MAPPROPERTY = 0x199,
  HEADER_ZC_NOTIFY_RANKING = 0x19a,
  HEADER_ZC_NOTIFY_EFFECT = 0x19b,
  HEADER_CZ_LOCALBROADCAST = 0x19c,
  HEADER_CZ_CHANGE_EFFECTSTATE = 0x19d,
  HEADER_ZC_START_CAPTURE = 0x19e,
  HEADER_CZ_TRYCAPTURE_MONSTER = 0x19f,
  HEADER_ZC_TRYCAPTURE_MONSTER = 0x1a0,
  HEADER_CZ_COMMAND_PET = 0x1a1,
  HEADER_ZC_PROPERTY_PET = 0x1a2,
  HEADER_ZC_FEED_PET = 0x1a3,
  HEADER_ZC_CHANGESTATE_PET = 0x1a4,
  HEADER_CZ_RENAME_PET = 0x1a5,
  HEADER_ZC_PETEGG_LIST = 0x1a6,
  HEADER_CZ_SELECT_PETEGG = 0x1a7,
  HEADER_CZ_PETEGG_INFO = 0x1a8,
  HEADER_CZ_PET_ACT = 0x1a9,
  HEADER_ZC_PET_ACT = 0x1aa,
  HEADER_ZC_PAR_CHANGE_USER = 0x1ab,
  HEADER_ZC_SKILL_UPDATE = 0x1ac,
  HEADER_ZC_MAKINGARROW_LIST = 0x1ad,
  HEADER_CZ_REQ_MAKINGARROW = 0x1ae,
  HEADER_CZ_REQ_CHANGECART = 0x1af,
  HEADER_ZC_NPCSPRITE_CHANGE = 0x1b0,
  HEADER_ZC_SHOWDIGIT = 0x1b1,
  HEADER_CZ_REQ_OPENSTORE2 = 0x1b2,
  HEADER_ZC_SHOW_IMAGE2 = 0x1b3,
  HEADER_ZC_CHANGE_GUILD = 0x1b4,
  HEADER_SC_BILLING_INFO = 0x1b5,
  HEADER_ZC_GUILD_INFO2 = 0x1b6,
  HEADER_CZ_GUILD_ZENY = 0x1b7,
  HEADER_ZC_GUILD_ZENY_ACK = 0x1b8,
  HEADER_ZC_DISPEL = 0x1b9,
  HEADER_CZ_REMOVE_AID = 0x1ba,
  HEADER_CZ_SHIFT = 0x1bb,
  HEADER_CZ_RECALL = 0x1bc,
  HEADER_CZ_RECALL_GID = 0x1bd,
  HEADER_AC_ASK_PNGAMEROOM = 0x1be,
  HEADER_CA_REPLY_PNGAMEROOM = 0x1bf,
  HEADER_CZ_REQ_REMAINTIME = 0x1c0,
  HEADER_ZC_REPLY_REMAINTIME = 0x1c1,
  HEADER_ZC_INFO_REMAINTIME = 0x1c2,
  HEADER_ZC_BROADCAST2 = 0x1c3,
  HEADER_ZC_ADD_ITEM_TO_STORE2 = 0x1c4,
  HEADER_ZC_ADD_ITEM_TO_CART2 = 0x1c5,
  HEADER_CS_REQ_ENCRYPTION = 0x1c6,
  HEADER_SC_ACK_ENCRYPTION = 0x1c7,
  HEADER_ZC_USE_ITEM_ACK2 = 0x1c8,
  HEADER_ZC_SKILL_ENTRY2 = 0x1c9,
  HEADER_CZ_REQMAKINGHOMUN = 0x1ca,
  HEADER_CZ_MONSTER_TALK = 0x1cb,
  HEADER_ZC_MONSTER_TALK = 0x1cc,
  HEADER_ZC_AUTOSPELLLIST = 0x1cd,
  HEADER_CZ_SELECTAUTOSPELL = 0x1ce,
  HEADER_ZC_DEVOTIONLIST = 0x1cf,
  HEADER_ZC_SPIRITS = 0x1d0,
  HEADER_ZC_BLADESTOP = 0x1d1,
  HEADER_ZC_COMBODELAY = 0x1d2,
  HEADER_ZC_SOUND = 0x1d3,
  HEADER_ZC_OPEN_EDITDLGSTR = 0x1d4,
  HEADER_CZ_INPUT_EDITDLGSTR = 0x1d5,
  HEADER_ZC_NOTIFY_MAPPROPERTY2 = 0x1d6,
  HEADER_ZC_SPRITE_CHANGE2 = 0x1d7,
  HEADER_ZC_NOTIFY_STANDENTRY2 = 0x1d8,
  HEADER_ZC_NOTIFY_NEWENTRY2 = 0x1d9,
  HEADER_ZC_NOTIFY_MOVEENTRY2 = 0x1da,
  HEADER_CA_REQ_HASH = 0x1db,
  HEADER_AC_ACK_HASH = 0x1dc,
  HEADER_CA_LOGIN2 = 0x1dd,
  HEADER_ZC_NOTIFY_SKILL2 = 0x1de,
  HEADER_CZ_REQ_ACCOUNTNAME = 0x1df,
  HEADER_ZC_ACK_ACCOUNTNAME = 0x1e0,
  HEADER_ZC_SPIRITS2 = 0x1e1,
  HEADER_ZC_REQ_COUPLE = 0x1e2,
  HEADER_CZ_JOIN_COUPLE = 0x1e3,
  HEADER_ZC_START_COUPLE = 0x1e4,
  HEADER_CZ_REQ_JOIN_COUPLE = 0x1e5,
  HEADER_ZC_COUPLENAME = 0x1e6,
  HEADER_CZ_DORIDORI = 0x1e7,
  HEADER_CZ_MAKE_GROUP2 = 0x1e8,
  HEADER_ZC_ADD_MEMBER_TO_GROUP2 = 0x1e9,
  HEADER_ZC_CONGRATULATION = 0x1ea,
  HEADER_ZC_NOTIFY_POSITION_TO_GUILDM = 0x1eb,
  HEADER_ZC_GUILD_MEMBER_MAP_CHANGE = 0x1ec,
  HEADER_CZ_CHOPOKGI = 0x1ed,
  HEADER_ZC_NORMAL_ITEMLIST2 = 0x1ee,
  HEADER_ZC_CART_NORMAL_ITEMLIST2 = 0x1ef,
  HEADER_ZC_STORE_NORMAL_ITEMLIST2 = 0x1f0,
  HEADER_AC_NOTIFY_ERROR = 0x1f1,
  HEADER_ZC_UPDATE_CHARSTAT2 = 0x1f2,
  HEADER_ZC_NOTIFY_EFFECT2 = 0x1f3,
  HEADER_ZC_REQ_EXCHANGE_ITEM2 = 0x1f4,
  HEADER_ZC_ACK_EXCHANGE_ITEM2 = 0x1f5,
  HEADER_ZC_REQ_BABY = 0x1f6,
  HEADER_CZ_JOIN_BABY = 0x1f7,
  HEADER_ZC_START_BABY = 0x1f8,
  HEADER_CZ_REQ_JOIN_BABY = 0x1f9,
  HEADER_CA_LOGIN3 = 0x1fa,
  HEADER_CH_DELETE_CHAR2 = 0x1fb,
  HEADER_ZC_REPAIRITEMLIST = 0x1fc,
  HEADER_CZ_REQ_ITEMREPAIR = 0x1fd,
  HEADER_ZC_ACK_ITEMREPAIR = 0x1fe,
  HEADER_ZC_HIGHJUMP = 0x1ff,
  HEADER_CA_CONNECT_INFO_CHANGED = 0x200,
  HEADER_ZC_FRIENDS_LIST = 0x201,
  HEADER_CZ_ADD_FRIENDS = 0x202,
  HEADER_CZ_DELETE_FRIENDS = 0x203,
  HEADER_CA_EXE_HASHCHECK = 0x204,
  HEADER_ZC_DIVORCE = 0x205,
  HEADER_ZC_FRIENDS_STATE = 0x206,
  HEADER_ZC_REQ_ADD_FRIENDS = 0x207,
  HEADER_CZ_ACK_REQ_ADD_FRIENDS = 0x208,
  HEADER_ZC_ADD_FRIENDS_LIST = 0x209,
  HEADER_ZC_DELETE_FRIENDS = 0x20a,
  HEADER_CH_EXE_HASHCHECK = 0x20b,
  HEADER_CZ_EXE_HASHCHECK = 0x20c,
  HEADER_HC_BLOCK_CHARACTER = 0x20d,
  HEADER_ZC_STARSKILL = 0x20e,
  HEADER_CZ_REQ_PVPPOINT = 0x20f,
  HEADER_ZC_ACK_PVPPOINT = 0x210,
  HEADER_ZH_MOVE_PVPWORLD = 0x211,
  HEADER_CZ_REQ_GIVE_MANNER_BYNAME = 0x212,
  HEADER_CZ_REQ_STATUS_GM = 0x213,
  HEADER_ZC_ACK_STATUS_GM = 0x214,
  HEADER_ZC_SKILLMSG = 0x215,
  HEADER_ZC_BABYMSG = 0x216,
  HEADER_CZ_BLACKSMITH_RANK = 0x217,
  HEADER_CZ_ALCHEMIST_RANK = 0x218,
  HEADER_ZC_BLACKSMITH_RANK = 0x219,
  HEADER_ZC_ALCHEMIST_RANK = 0x21a,
  HEADER_ZC_BLACKSMITH_POINT = 0x21b,
  HEADER_ZC_ALCHEMIST_POINT = 0x21c,
  HEADER_CZ_LESSEFFECT = 0x21d,
  HEADER_ZC_LESSEFFECT = 0x21e,
  HEADER_ZC_NOTIFY_PKINFO = 0x21f,
  HEADER_ZC_NOTIFY_CRAZYKILLER = 0x220,
  HEADER_ZC_NOTIFY_WEAPONITEMLIST = 0x221,
  HEADER_CZ_REQ_WEAPONREFINE = 0x222,
  HEADER_ZC_ACK_WEAPONREFINE = 0x223,
  HEADER_ZC_TAEKWON_POINT = 0x224,
  HEADER_CZ_TAEKWON_RANK = 0x225,
  HEADER_ZC_TAEKWON_RANK = 0x226,
  HEADER_ZC_GAME_GUARD = 0x227,
  HEADER_CZ_ACK_GAME_GUARD = 0x228,
  HEADER_ZC_STATE_CHANGE3 = 0x229,
  HEADER_ZC_NOTIFY_STANDENTRY3 = 0x22a,
  HEADER_ZC_NOTIFY_NEWENTRY3 = 0x22b,
  HEADER_ZC_NOTIFY_MOVEENTRY3 = 0x22c,
  HEADER_CZ_COMMAND_MER = 0x22d,
  HEADER_ZC_PROPERTY_HOMUN = 0x22e,
  HEADER_ZC_FEED_MER = 0x22f,
  HEADER_ZC_CHANGESTATE_MER = 0x230,
  HEADER_CZ_RENAME_MER = 0x231,
  HEADER_CZ_REQUEST_MOVENPC = 0x232,
  HEADER_CZ_REQUEST_ACTNPC = 0x233,
  HEADER_CZ_REQUEST_MOVETOOWNER = 0x234,
  HEADER_ZC_HOSKILLINFO_LIST = 0x235,
  HEADER_ZC_KILLER_POINT = 0x236,
  HEADER_CZ_KILLER_RANK = 0x237,
  HEADER_ZC_KILLER_RANK = 0x238,
  HEADER_ZC_HOSKILLINFO_UPDATE = 0x239,
  HEADER_ZC_REQ_STORE_PASSWORD = 0x23a,
  HEADER_CZ_ACK_STORE_PASSWORD = 0x23b,
  HEADER_ZC_RESULT_STORE_PASSWORD = 0x23c,
  HEADER_AC_EVENT_RESULT = 0x23d,
  HEADER_HC_REQUEST_CHARACTER_PASSWORD = 0x23e,
  HEADER_CZ_MAIL_GET_LIST = 0x23f,
  HEADER_ZC_MAIL_REQ_GET_LIST = 0x240,
  HEADER_CZ_MAIL_OPEN = 0x241,
  HEADER_ZC_MAIL_REQ_OPEN = 0x242,
  HEADER_CZ_MAIL_DELETE = 0x243,
  HEADER_CZ_MAIL_GET_ITEM = 0x244,
  HEADER_ZC_MAIL_REQ_GET_ITEM = 0x245,
  HEADER_CZ_MAIL_RESET_ITEM = 0x246,
  HEADER_CZ_MAIL_ADD_ITEM = 0x247,
  HEADER_CZ_MAIL_SEND = 0x248,
  HEADER_ZC_MAIL_REQ_SEND = 0x249,
  HEADER_ZC_MAIL_RECEIVE = 0x24a,
  HEADER_CZ_AUCTION_CREATE = 0x24b,
  HEADER_CZ_AUCTION_ADD_ITEM = 0x24c,
  HEADER_CZ_AUCTION_ADD = 0x24d,
  HEADER_CZ_AUCTION_ADD_CANCEL = 0x24e,
  HEADER_CZ_AUCTION_BUY = 0x24f,
  HEADER_ZC_AUCTION_RESULT = 0x250,
  HEADER_CZ_AUCTION_ITEM_SEARCH = 0x251,
  HEADER_ZC_AUCTION_ITEM_REQ_SEARCH = 0x252,
  HEADER_ZC_STARPLACE = 0x253,
  HEADER_CZ_AGREE_STARPLACE = 0x254,
  HEADER_ZC_ACK_MAIL_ADD_ITEM = 0x255,
  HEADER_ZC_ACK_AUCTION_ADD_ITEM = 0x256,
  HEADER_ZC_ACK_MAIL_DELETE = 0x257,
  HEADER_CA_REQ_GAME_GUARD_CHECK = 0x258,
  HEADER_AC_ACK_GAME_GUARD = 0x259,
  HEADER_ZC_MAKINGITEM_LIST = 0x25a,
  HEADER_CZ_REQ_MAKINGITEM = 0x25b,
  HEADER_CZ_AUCTION_REQ_MY_INFO = 0x25c,
  HEADER_CZ_AUCTION_REQ_MY_SELL_STOP = 0x25d,
  HEADER_ZC_AUCTION_ACK_MY_SELL_STOP = 0x25e,
  HEADER_ZC_AUCTION_WINDOWS = 0x25f,
  HEADER_ZC_MAIL_WINDOWS = 0x260,
  HEADER_AC_REQ_LOGIN_OLDEKEY = 0x261,
  HEADER_AC_REQ_LOGIN_NEWEKEY = 0x262,
  HEADER_AC_REQ_LOGIN_CARDPASS = 0x263,
  HEADER_CA_ACK_LOGIN_OLDEKEY = 0x264,
  HEADER_CA_ACK_LOGIN_NEWEKEY = 0x265,
  HEADER_CA_ACK_LOGIN_CARDPASS = 0x266,
  HEADER_AC_ACK_EKEY_FAIL_NOTEXIST = 0x267,
  HEADER_AC_ACK_EKEY_FAIL_NOTUSESEKEY = 0x268,
  HEADER_AC_ACK_EKEY_FAIL_NOTUSEDEKEY = 0x269,
  HEADER_AC_ACK_EKEY_FAIL_AUTHREFUSE = 0x26a,
  HEADER_AC_ACK_EKEY_FAIL_INPUTEKEY = 0x26b,
  HEADER_AC_ACK_EKEY_FAIL_NOTICE = 0x26c,
  HEADER_AC_ACK_EKEY_FAIL_NEEDCARDPASS = 0x26d,
  HEADER_AC_ACK_AUTHEKEY_FAIL_NOTMATCHCARDPASS = 0x26e,
  HEADER_AC_ACK_FIRST_LOGIN = 0x26f,
  HEADER_AC_REQ_LOGIN_ACCOUNT_INFO = 0x270,
  HEADER_CA_ACK_LOGIN_ACCOUNT_INFO = 0x271,
  HEADER_AC_ACK_PT_ID_INFO = 0x272,
  HEADER_CZ_REQ_MAIL_RETURN = 0x273,
  HEADER_ZC_ACK_MAIL_RETURN = 0x274,
  HEADER_CH_ENTER2 = 0x275,
  HEADER_AC_ACCEPT_LOGIN2 = 0x276,
  HEADER_CA_LOGIN_PCBANG = 0x277,
  HEADER_ZC_NOTIFY_PCBANG = 0x278,
  HEADER_CZ_HUNTINGLIST = 0x279,
  HEADER_ZC_HUNTINGLIST = 0x27a,
  HEADER_ZC_PCBANG_EFFECT = 0x27b,
  HEADER_CA_LOGIN4 = 0x27c,
  HEADER_ZC_PROPERTY_MERCE = 0x27d,
  HEADER_ZC_SHANDA_PROTECT = 0x27e,
  HEADER_CA_CLIENT_TYPE = 0x27f,
  HEADER_ZC_GANGSI_POINT = 0x280,
  HEADER_CZ_GANGSI_RANK = 0x281,
  HEADER_ZC_GANGSI_RANK = 0x282,
  HEADER_ZC_AID = 0x283,
  HEADER_ZC_NOTIFY_EFFECT3 = 0x284,
  HEADER_ZC_DEATH_QUESTION = 0x285,
  HEADER_CZ_DEATH_QUESTION = 0x286,
  HEADER_ZC_PC_CASH_POINT_ITEMLIST = 0x287,
  HEADER_CZ_PC_BUY_CASH_POINT_ITEM = 0x288,
  HEADER_ZC_PC_CASH_POINT_UPDATE = 0x289,
  HEADER_ZC_NPC_SHOWEFST_UPDATE = 0x28a,
  HEADER_HC_CHARNOTBEENSELECTED = 0x28b,
  HEADER_CH_SELECT_CHAR_GOINGTOBEUSED = 0x28c,
  HEADER_CH_REQ_IS_VALID_CHARNAME = 0x28d,
  HEADER_HC_ACK_IS_VALID_CHARNAME = 0x28e,
  HEADER_CH_REQ_CHANGE_CHARNAME = 0x28f,
  HEADER_HC_ACK_CHANGE_CHARNAME = 0x290,
  HEADER_ZC_MSG = 0x291,
  HEADER_CZ_STANDING_RESURRECTION = 0x292,
  HEADER_ZC_BOSS_INFO = 0x293,
  HEADER_ZC_READ_BOOK = 0x294,
  HEADER_ZC_EQUIPMENT_ITEMLIST2 = 0x295,
  HEADER_ZC_STORE_EQUIPMENT_ITEMLIST2 = 0x296,
  HEADER_ZC_CART_EQUIPMENT_ITEMLIST2 = 0x297,
  HEADER_ZC_CASH_TIME_COUNTER = 0x298,
  HEADER_ZC_CASH_ITEM_DELETE = 0x299,
  HEADER_ZC_ITEM_PICKUP_ACK2 = 0x29a,
  HEADER_ZC_MER_INIT = 0x29b,
  HEADER_ZC_MER_PROPERTY = 0x29c,
  HEADER_ZC_MER_SKILLINFO_LIST = 0x29d,
  HEADER_ZC_MER_SKILLINFO_UPDATE = 0x29e,
  HEADER_CZ_MER_COMMAND = 0x29f,
  UNUSED_HEADER_CZ_MER_USE_SKILL = 0x2a0,
  UNUSED_HEADER_CZ_MER_UPGRADE_SKILLLEVEL = 0x2a1,
  HEADER_ZC_MER_PAR_CHANGE = 0x2a2,
  HEADER_ZC_GAMEGUARD_LINGO_KEY = 0x2a3,
  HEADER_CZ_GAMEGUARD_LINGO_READY = 0x2a4,
  HEADER_CZ_KSY_EVENT = 0x2a5,
  HEADER_ZC_HACKSH_CPX_MSG = 0x2a6,
  HEADER_CZ_HACKSH_CPX_MSG = 0x2a7,
  HEADER_ZC_HACKSHIELD_CRC_MSG = 0x2a8,
  HEADER_CZ_HACKSHIELD_CRC_MSG = 0x2a9,
  HEADER_ZC_REQ_CASH_PASSWORD = 0x2aa,
  HEADER_CZ_ACK_CASH_PASSWORD = 0x2ab,
  HEADER_ZC_RESULT_CASH_PASSWORD = 0x2ac,
  HEADER_AC_REQUEST_SECOND_PASSWORD = 0x2ad,
  HEADER_ZC_SRPACKET_INIT = 0x2ae,
  HEADER_CZ_SRPACKET_START = 0x2af,
  HEADER_CA_LOGIN_CHANNEL = 0x2b0,
  HEADER_ZC_ALL_QUEST_LIST = 0x2b1,
  HEADER_ZC_ALL_QUEST_MISSION = 0x2b2,
  HEADER_ZC_ADD_QUEST = 0x2b3,
  HEADER_ZC_DEL_QUEST = 0x2b4,
  HEADER_ZC_UPDATE_MISSION_HUNT = 0x2b5,
  HEADER_CZ_ACTIVE_QUEST = 0x2b6,
  HEADER_ZC_ACTIVE_QUEST = 0x2b7,
  HEADER_ZC_ITEM_PICKUP_PARTY = 0x2b8,
  HEADER_ZC_SHORTCUT_KEY_LIST = 0x2b9,
  HEADER_CZ_SHORTCUT_KEY_CHANGE = 0x2ba,
  HEADER_ZC_EQUIPITEM_DAMAGED = 0x2bb,
  HEADER_ZC_NOTIFY_PCBANG_PLAYING_TIME = 0x2bc,
  HEADER_ZC_SRCRYPTOR2_INIT = 0x2bd,
  HEADER_CZ_SRCRYPTOR2_START = 0x2be,
  HEADER_ZC_SRPACKETR2_INIT = 0x2bf,
  HEADER_CZ_SRPACKETR2_START = 0x2c0,
  HEADER_ZC_NPC_CHAT = 0x2c1,
  HEADER_ZC_FORMATSTRING_MSG = 0x2c2,
  UNUSED_HEADER_CZ_FORMATSTRING_MSG_RES = 0x2c3,
  HEADER_CZ_PARTY_JOIN_REQ = 0x2c4,
  HEADER_ZC_PARTY_JOIN_REQ_ACK = 0x2c5,
  HEADER_ZC_PARTY_JOIN_REQ = 0x2c6,
  HEADER_CZ_PARTY_JOIN_REQ_ACK = 0x2c7,
  HEADER_CZ_PARTY_CONFIG = 0x2c8,
  HEADER_ZC_PARTY_CONFIG = 0x2c9,
  HEADER_HC_REFUSE_SELECTCHAR = 0x2ca,
  HEADER_ZC_MEMORIALDUNGEON_SUBSCRIPTION_INFO = 0x2cb,
  HEADER_ZC_MEMORIALDUNGEON_SUBSCRIPTION_NOTIFY = 0x2cc,
  HEADER_ZC_MEMORIALDUNGEON_INFO = 0x2cd,
  HEADER_ZC_MEMORIALDUNGEON_NOTIFY = 0x2ce,
  HEADER_CZ_MEMORIALDUNGEON_COMMAND = 0x2cf,
  HEADER_ZC_EQUIPMENT_ITEMLIST3 = 0x2d0,
  HEADER_ZC_STORE_EQUIPMENT_ITEMLIST3 = 0x2d1,
  HEADER_ZC_CART_EQUIPMENT_ITEMLIST3 = 0x2d2,
  HEADER_ZC_NOTIFY_BIND_ON_EQUIP = 0x2d3,
  HEADER_ZC_ITEM_PICKUP_ACK3 = 0x2d4,
  HEADER_ZC_ISVR_DISCONNECT = 0x2d5,
  HEADER_CZ_EQUIPWIN_MICROSCOPE = 0x2d6,
  HEADER_ZC_EQUIPWIN_MICROSCOPE = 0x2d7,
  HEADER_CZ_CONFIG = 0x2d8,
  HEADER_ZC_CONFIG = 0x2d9,
  HEADER_ZC_CONFIG_NOTIFY = 0x2da,
  HEADER_CZ_BATTLEFIELD_CHAT = 0x2db,
  HEADER_ZC_BATTLEFIELD_CHAT = 0x2dc,
  HEADER_ZC_BATTLEFIELD_NOTIFY_CAMPINFO = 0x2dd,
  HEADER_ZC_BATTLEFIELD_NOTIFY_POINT = 0x2de,
  HEADER_ZC_BATTLEFIELD_NOTIFY_POSITION = 0x2df,
  HEADER_ZC_BATTLEFIELD_NOTIFY_HP = 0x2e0,
  HEADER_ZC_NOTIFY_ACT2 = 0x2e1,
  HEADER_CZ_USE_ITEM_NEW_JAPEN = 0x2e2,
  HEADER_CZ_USE_SKILL_NEW_JAPEN = 0x2e3,
  HEADER_CZ_ITEM_PICKUP_NEW_JAPEN = 0x2e4,
  HEADER_CZ_REQUEST_MOVE_NEW_JAPEN = 0x2e5,
  HEADER_CZ_BOT_CHECK = 0x2e6,
  HEADER_ZC_MAPPROPERTY = 0x2e7,
  HEADER_ZC_NORMAL_ITEMLIST3 = 0x2e8,
  HEADER_ZC_CART_NORMAL_ITEMLIST3 = 0x2e9,
  HEADER_ZC_STORE_NORMAL_ITEMLIST3 = 0x2ea,
  HEADER_ZC_ACCEPT_ENTER2 = 0x2eb,
  HEADER_ZC_NOTIFY_MOVEENTRY4 = 0x2ec,
  HEADER_ZC_NOTIFY_NEWENTRY4 = 0x2ed,
  HEADER_ZC_NOTIFY_STANDENTRY4 = 0x2ee,
  HEADER_ZC_NOTIFY_FONT = 0x2ef,
  HEADER_ZC_PROGRESS = 0x2f0,
  HEADER_CZ_PROGRESS = 0x2f1,
  HEADER_ZC_PROGRESS_CANCEL = 0x2f2,
  HEADER_CZ_IRMAIL_SEND = 0x2f3,
  HEADER_ZC_IRMAIL_SEND_RES = 0x2f4,
  HEADER_ZC_IRMAIL_NOTIFY = 0x2f5,
  HEADER_CZ_IRMAIL_LIST = 0x2f6,
  HEADER_CZ_OPEN_SIMPLE_CASHSHOP_ITEMLIST = 0x35c,
  HEADER_ZC_SIMPLE_CASHSHOP_POINT_ITEMLIST = 0x35d,
  HEADER_CZ_CLOSE_WINDOW = 0x35e,
  HEADER_CZ_REQUEST_MOVE2 = 0x35f,
  HEADER_CZ_REQUEST_TIME2 = 0x360,
  HEADER_CZ_CHANGE_DIRECTION2 = 0x361,
  HEADER_CZ_ITEM_PICKUP2 = 0x362,
  HEADER_CZ_ITEM_THROW2 = 0x363,
  HEADER_CZ_MOVE_ITEM_FROM_BODY_TO_STORE2 = 0x364,
  HEADER_CZ_MOVE_ITEM_FROM_STORE_TO_BODY2 = 0x365,
  HEADER_CZ_USE_SKILL_TOGROUND2 = 0x366,
  HEADER_CZ_USE_SKILL_TOGROUND_WITHTALKBOX2 = 0x367,
  HEADER_CZ_REQNAME2 = 0x368,
  HEADER_CZ_REQNAME_BYGID2 = 0x369,
  HEADER_AHC_GAME_GUARD = 0x3dd,
  HEADER_CAH_ACK_GAME_GUARD = 0x3de,
  HEADER_ZC_WAITINGROOM_PARTYPLAY_JOIN = 0x3df,
  HEADER_CZ_WAITINGROOM_PARTYPLAY_JOIN_RESULT = 0x3e0,
  HEADER_ZC_WAITINGROOM_SUBSCRIPTION_RESULT = 0x3e1,
  HEADER_CZ_ENTER2 = 0x436,
  HEADER_CZ_REQUEST_ACT2 = 0x437,
  HEADER_CZ_USE_SKILL2 = 0x438,
  HEADER_CZ_USE_ITEM2 = 0x439,
  HEADER_ZC_REQ_CRACKPROOF = 0x43a,
  HEADER_CZ_ACK_CRACKPROOF = 0x43b,
  HEADER_ZC_CRACKPROOF_ERRCODE = 0x43c,
  HEADER_ZC_SKILL_POSTDELAY = 0x43d,
  HEADER_ZC_SKILL_POSTDELAY_LIST = 0x43e,
  HEADER_ZC_MSG_STATE_CHANGE2 = 0x43f,
  HEADER_ZC_MILLENNIUMSHIELD = 0x440,
  HEADER_ZC_SKILLINFO_DELETE = 0x441,
  HEADER_ZC_SKILL_SELECT_REQUEST = 0x442,
  HEADER_CZ_SKILL_SELECT_RESPONSE = 0x443,
  HEADER_ZC_SIMPLE_CASH_POINT_ITEMLIST = 0x444,
  HEADER_CZ_SIMPLE_BUY_CASH_POINT_ITEM = 0x445,
  HEADER_ZC_QUEST_NOTIFY_EFFECT = 0x446,
  HEADER_CZ_BLOCKING_PLAY_CANCEL = 0x447,
  HEADER_HC_CHARACTER_LIST = 0x448,
  HEADER_ZC_HACKSH_ERROR_MSG = 0x449,
  HEADER_CZ_CLIENT_VERSION = 0x44a,
  HEADER_CZ_CLOSE_SIMPLECASH_SHOP = 0x44b,
  HEADER_ZC_ES_RESULT = 0x7d0,
  HEADER_CZ_ES_GET_LIST = 0x7d1,
  HEADER_ZC_ES_LIST = 0x7d2,
  HEADER_CZ_ES_CHOOSE = 0x7d3,
  HEADER_CZ_ES_CANCEL = 0x7d4,
  HEADER_ZC_ES_READY = 0x7d5,
  HEADER_ZC_ES_GOTO = 0x7d6,
  HEADER_CZ_GROUPINFO_CHANGE_V2 = 0x7d7,
  HEADER_ZC_REQ_GROUPINFO_CHANGE_V2 = 0x7d8,
  HEADER_ZC_SHORTCUT_KEY_LIST_V2 = 0x7d9,
  HEADER_CZ_CHANGE_GROUP_MASTER = 0x7da,
  HEADER_ZC_HO_PAR_CHANGE = 0x7db,
  HEADER_CZ_SEEK_PARTY = 0x7dc,
  HEADER_ZC_SEEK_PARTY = 0x7dd,
  HEADER_CZ_SEEK_PARTY_MEMBER = 0x7de,
  HEADER_ZC_SEEK_PARTY_MEMBER = 0x7df,
  HEADER_ZC_ES_NOTI_MYINFO = 0x7e0,
  HEADER_ZC_SKILLINFO_UPDATE2 = 0x7e1,
  HEADER_ZC_MSG_VALUE = 0x7e2,
  HEADER_ZC_ITEMLISTWIN_OPEN = 0x7e3,
  HEADER_CZ_ITEMLISTWIN_RES = 0x7e4,
  HEADER_CH_ENTER_CHECKBOT = 0x7e5,
  HEADER_ZC_MSG_SKILL = 0x7e6,
  HEADER_CH_CHECKBOT = 0x7e7,
  HEADER_HC_CHECKBOT = 0x7e8,
  HEADER_HC_CHECKBOT_RESULT = 0x7e9,
  HEADER_CZ_BATTLE_FIELD_LIST = 0x7ea,
  HEADER_ZC_BATTLE_FIELD_LIST = 0x7eb,
  HEADER_CZ_JOIN_BATTLE_FIELD = 0x7ec,
  HEADER_ZC_JOIN_BATTLE_FIELD = 0x7ed,
  HEADER_CZ_CANCEL_BATTLE_FIELD = 0x7ee,
  HEADER_ZC_CANCEL_BATTLE_FIELD = 0x7ef,
  HEADER_CZ_REQ_BATTLE_STATE_MONITOR = 0x7f0,
  HEADER_ZC_ACK_BATTLE_STATE_MONITOR = 0x7f1,
  HEADER_ZC_BATTLE_NOTI_START_STEP = 0x7f2,
  HEADER_ZC_BATTLE_JOIN_NOTI_DEFER = 0x7f3,
  HEADER_ZC_BATTLE_JOIN_DISABLE_STATE = 0x7f4,
  HEADER_CZ_GM_FULLSTRIP = 0x7f5,
  HEADER_ZC_NOTIFY_EXP = 0x7f6,
  HEADER_ZC_NOTIFY_MOVEENTRY7 = 0x7f7,
  HEADER_ZC_NOTIFY_NEWENTRY5 = 0x7f8,
  HEADER_ZC_NOTIFY_STANDENTRY5 = 0x7f9,
  HEADER_ZC_DELETE_ITEM_FROM_BODY = 0x7fa,
  HEADER_ZC_USESKILL_ACK2 = 0x7fb,
  HEADER_ZC_CHANGE_GROUP_MASTER = 0x7fc,
  HEADER_ZC_BROADCASTING_SPECIAL_ITEM_OBTAIN = 0x7fd,
  HEADER_ZC_PLAY_NPC_BGM = 0x7fe,
  HEADER_ZC_DEFINE_CHECK = 0x7ff,
  HEADER_ZC_PC_PURCHASE_ITEMLIST_FROMMC2 = 0x800,
  HEADER_CZ_PC_PURCHASE_ITEMLIST_FROMMC2 = 0x801,
  HEADER_CZ_PARTY_BOOKING_REQ_REGISTER = 0x802,
  HEADER_ZC_PARTY_BOOKING_ACK_REGISTER = 0x803,
  HEADER_CZ_PARTY_BOOKING_REQ_SEARCH = 0x804,
  HEADER_ZC_PARTY_BOOKING_ACK_SEARCH = 0x805,
  HEADER_CZ_PARTY_BOOKING_REQ_DELETE = 0x806,
  HEADER_ZC_PARTY_BOOKING_ACK_DELETE = 0x807,
  HEADER_CZ_PARTY_BOOKING_REQ_UPDATE = 0x808,
  HEADER_ZC_PARTY_BOOKING_NOTIFY_INSERT = 0x809,
  HEADER_ZC_PARTY_BOOKING_NOTIFY_UPDATE = 0x80a,
  HEADER_ZC_PARTY_BOOKING_NOTIFY_DELETE = 0x80b,
  HEADER_CZ_SIMPLE_CASH_BTNSHOW = 0x80c,
  HEADER_ZC_SIMPLE_CASH_BTNSHOW = 0x80d,
  HEADER_ZC_NOTIFY_HP_TO_GROUPM_R2 = 0x80e,
  HEADER_ZC_ADD_EXCHANGE_ITEM2 = 0x80f,
  HEADER_ZC_OPEN_BUYING_STORE = 0x810,
  HEADER_CZ_REQ_OPEN_BUYING_STORE = 0x811,
  HEADER_ZC_FAILED_OPEN_BUYING_STORE_TO_BUYER = 0x812,
  HEADER_ZC_MYITEMLIST_BUYING_STORE = 0x813,
  HEADER_ZC_BUYING_STORE_ENTRY = 0x814,
  HEADER_CZ_REQ_CLOSE_BUYING_STORE = 0x815,
  HEADER_ZC_DISAPPEAR_BUYING_STORE_ENTRY = 0x816,
  HEADER_CZ_REQ_CLICK_TO_BUYING_STORE = 0x817,
  HEADER_ZC_ACK_ITEMLIST_BUYING_STORE = 0x818,
  HEADER_CZ_REQ_TRADE_BUYING_STORE = 0x819,
  HEADER_ZC_FAILED_TRADE_BUYING_STORE_TO_BUYER = 0x81a,
  HEADER_ZC_UPDATE_ITEM_FROM_BUYING_STORE = 0x81b,
  HEADER_ZC_ITEM_DELETE_BUYING_STORE = 0x81c,
  HEADER_ZC_EL_INIT = 0x81d,
  HEADER_ZC_EL_PAR_CHANGE = 0x81e,
  HEADER_ZC_BROADCAST4 = 0x81f,
  HEADER_ZC_COSTUME_SPRITE_CHANGE = 0x820,
  HEADER_AC_OTP_USER = 0x821,
  HEADER_CA_OTP_AUTH_REQ = 0x822,
  HEADER_AC_OTP_AUTH_ACK = 0x823,
  HEADER_ZC_FAILED_TRADE_BUYING_STORE_TO_SELLER = 0x824,
  HEADER_CA_SSO_LOGIN_REQ = 0x825,
  HEADER_AC_SSO_LOGIN_ACK = 0x826,
  HEADER_CH_DELETE_CHAR3_RESERVED = 0x827,
  HEADER_HC_DELETE_CHAR3_RESERVED = 0x828,
  HEADER_CH_DELETE_CHAR3 = 0x829,
  HEADER_HC_DELETE_CHAR3 = 0x82a,
  HEADER_CH_DELETE_CHAR3_CANCEL = 0x82b,
  HEADER_HC_DELETE_CHAR3_CANCEL = 0x82c,
  HEADER_HC_ACCEPT_ENTER2 = 0x82d,
  HEADER_CZ_SEARCH_STORE_INFO = 0x835,
  HEADER_ZC_SEARCH_STORE_INFO_ACK = 0x836,
  HEADER_ZC_SEARCH_STORE_INFO_FAILED = 0x837,
  HEADER_CZ_SEARCH_STORE_INFO_NEXT_PAGE = 0x838,
  HEADER_ZC_ACK_BAN_GUILD_SSO = 0x839,
  HEADER_ZC_OPEN_SEARCH_STORE_INFO = 0x83a,
  HEADER_CZ_CLOSE_SEARCH_STORE_INFO = 0x83b,
  HEADER_CZ_SSILIST_ITEM_CLICK = 0x83c,
  HEADER_ZC_SSILIST_ITEM_CLICK_ACK = 0x83d,
  HEADER_AC_REFUSE_LOGIN_R2 = 0x83e,
  HEADER_ZC_SEARCH_STORE_OPEN_INFO = 0x83f,
  HEADER_HC_NOTIFY_ACCESSIBLE_MAPNAME = 0x840,
  HEADER_CH_SELECT_ACCESSIBLE_MAPNAME = 0x841,
  HEADER_CZ_RECALL_SSO = 0x842,
  HEADER_CZ_REMOVE_AID_SSO = 0x843,
  HEADER_CZ_SE_CASHSHOP_OPEN = 0x844,
  HEADER_ZC_SE_CASHSHOP_OPEN = 0x845,
  HEADER_CZ_REQ_SE_CASH_TAB_CODE = 0x846,
  HEADER_ZC_ACK_SE_CASH_ITEM_LIST = 0x847,
  HEADER_CZ_SE_PC_BUY_CASHITEM_LIST = 0x848,
  HEADER_ZC_SE_PC_BUY_CASHITEM_RESULT = 0x849,
  HEADER_CZ_SE_CASHSHOP_CLOSE = 0x84a,
  HEADER_ZC_ITEM_FALL_ENTRY4 = 0x84b,
  HEADER_CZ_MACRO_USE_SKILL = 0x84c,
  HEADER_CZ_MACRO_USE_SKILL_TOGROUND = 0x84d,
  HEADER_CZ_MACRO_REQUEST_MOVE = 0x84e,
  HEADER_CZ_MACRO_ITEM_PICKUP = 0x84f,
  HEADER_CZ_MACRO_REQUEST_ACT = 0x850,
  HEADER_ZC_GPK_DYNCODE = 0x851,
  HEADER_CZ_GPK_DYNCODE_RELOAD = 0x852,
  HEADER_ZC_GPK_AUTH = 0x853,
  HEADER_CZ_GPK_AUTH = 0x854,
  HEADER_ZC_MACRO_ITEMPICKUP_FAIL = 0x855,
  HEADER_ZC_NOTIFY_MOVEENTRY8 = 0x856,
  HEADER_ZC_NOTIFY_STANDENTRY7 = 0x857,
  HEADER_ZC_NOTIFY_NEWENTRY6 = 0x858,
  HEADER_ZC_EQUIPWIN_MICROSCOPE2 = 0x859,
  HEADER_ZC_REASSEMBLY_AUTH01 = 0x85a,
  HEADER_ZC_REASSEMBLY_AUTH02 = 0x85b,
  HEADER_ZC_REASSEMBLY_AUTH03 = 0x85c,
  HEADER_ZC_REASSEMBLY_AUTH04 = 0x85d,
  HEADER_ZC_REASSEMBLY_AUTH05 = 0x85e,
  HEADER_ZC_REASSEMBLY_AUTH06 = 0x85f,
  HEADER_ZC_REASSEMBLY_AUTH07 = 0x860,
  HEADER_ZC_REASSEMBLY_AUTH08 = 0x861,
  HEADER_ZC_REASSEMBLY_AUTH09 = 0x862,
  HEADER_ZC_REASSEMBLY_AUTH10 = 0x863,
  HEADER_ZC_REASSEMBLY_AUTH11 = 0x864,
  HEADER_ZC_REASSEMBLY_AUTH12 = 0x865,
  HEADER_ZC_REASSEMBLY_AUTH13 = 0x866,
  HEADER_ZC_REASSEMBLY_AUTH14 = 0x867,
  HEADER_ZC_REASSEMBLY_AUTH15 = 0x868,
  HEADER_ZC_REASSEMBLY_AUTH16 = 0x869,
  HEADER_ZC_REASSEMBLY_AUTH17 = 0x86a,
  HEADER_ZC_REASSEMBLY_AUTH18 = 0x86b,
  HEADER_ZC_REASSEMBLY_AUTH19 = 0x86c,
  HEADER_ZC_REASSEMBLY_AUTH20 = 0x86d,
  HEADER_ZC_REASSEMBLY_AUTH21 = 0x86e,
  HEADER_ZC_REASSEMBLY_AUTH22 = 0x86f,
  HEADER_ZC_REASSEMBLY_AUTH23 = 0x870,
  HEADER_ZC_REASSEMBLY_AUTH24 = 0x871,
  HEADER_ZC_REASSEMBLY_AUTH25 = 0x872,
  HEADER_ZC_REASSEMBLY_AUTH26 = 0x873,
  HEADER_ZC_REASSEMBLY_AUTH27 = 0x874,
  HEADER_ZC_REASSEMBLY_AUTH28 = 0x875,
  HEADER_ZC_REASSEMBLY_AUTH29 = 0x876,
  HEADER_ZC_REASSEMBLY_AUTH30 = 0x877,
  HEADER_ZC_REASSEMBLY_AUTH31 = 0x878,
  HEADER_ZC_REASSEMBLY_AUTH32 = 0x879,
  HEADER_ZC_REASSEMBLY_AUTH33 = 0x87a,
  HEADER_ZC_REASSEMBLY_AUTH34 = 0x87b,
  HEADER_ZC_REASSEMBLY_AUTH35 = 0x87c,
  HEADER_ZC_REASSEMBLY_AUTH36 = 0x87d,
  HEADER_ZC_REASSEMBLY_AUTH37 = 0x87e,
  HEADER_ZC_REASSEMBLY_AUTH38 = 0x87f,
  HEADER_ZC_REASSEMBLY_AUTH39 = 0x880,
  HEADER_ZC_REASSEMBLY_AUTH40 = 0x881,
  HEADER_ZC_REASSEMBLY_AUTH41 = 0x882,
  HEADER_ZC_REASSEMBLY_AUTH42 = 0x883,
  HEADER_CZ_REASSEMBLY_AUTH01 = 0x884,
  HEADER_CZ_REASSEMBLY_AUTH02 = 0x885,
  HEADER_CZ_REASSEMBLY_AUTH03 = 0x886,
  HEADER_CZ_REASSEMBLY_AUTH04 = 0x887,
  HEADER_CZ_REASSEMBLY_AUTH05 = 0x888,
  HEADER_CZ_REASSEMBLY_AUTH06 = 0x889,
  HEADER_CZ_REASSEMBLY_AUTH07 = 0x88a,
  HEADER_CZ_REASSEMBLY_AUTH08 = 0x88b,
  HEADER_CZ_REASSEMBLY_AUTH09 = 0x88c,
  HEADER_CZ_REASSEMBLY_AUTH10 = 0x88d,
  HEADER_CZ_REASSEMBLY_AUTH11 = 0x88e,
  HEADER_CZ_REASSEMBLY_AUTH12 = 0x88f,
  HEADER_CZ_REASSEMBLY_AUTH13 = 0x890,
  HEADER_CZ_REASSEMBLY_AUTH14 = 0x891,
  HEADER_CZ_REASSEMBLY_AUTH15 = 0x892,
  HEADER_CZ_REASSEMBLY_AUTH16 = 0x893,
  HEADER_CZ_REASSEMBLY_AUTH17 = 0x894,
  HEADER_CZ_REASSEMBLY_AUTH18 = 0x895,
  HEADER_CZ_REASSEMBLY_AUTH19 = 0x896,
  HEADER_CZ_REASSEMBLY_AUTH20 = 0x897,
  HEADER_CZ_REASSEMBLY_AUTH21 = 0x898,
  HEADER_CZ_REASSEMBLY_AUTH22 = 0x899,
  HEADER_CZ_REASSEMBLY_AUTH23 = 0x89a,
  HEADER_CZ_REASSEMBLY_AUTH24 = 0x89b,
  HEADER_CZ_REASSEMBLY_AUTH25 = 0x89c,
  HEADER_CZ_REASSEMBLY_AUTH26 = 0x89d,
  HEADER_CZ_REASSEMBLY_AUTH27 = 0x89e,
  HEADER_CZ_REASSEMBLY_AUTH28 = 0x89f,
  HEADER_CZ_REASSEMBLY_AUTH29 = 0x8a0,
  HEADER_CZ_REASSEMBLY_AUTH30 = 0x8a1,
  HEADER_CZ_REASSEMBLY_AUTH31 = 0x8a2,
  HEADER_CZ_REASSEMBLY_AUTH32 = 0x8a3,
  HEADER_CZ_REASSEMBLY_AUTH33 = 0x8a4,
  HEADER_CZ_REASSEMBLY_AUTH34 = 0x8a5,
  HEADER_CZ_REASSEMBLY_AUTH35 = 0x8a6,
  HEADER_CZ_REASSEMBLY_AUTH36 = 0x8a7,
  HEADER_CZ_REASSEMBLY_AUTH37 = 0x8a8,
  HEADER_CZ_REASSEMBLY_AUTH38 = 0x8a9,
  HEADER_CZ_REASSEMBLY_AUTH39 = 0x8aa,
  HEADER_CZ_REASSEMBLY_AUTH40 = 0x8ab,
  HEADER_CZ_REASSEMBLY_AUTH41 = 0x8ac,
  HEADER_CZ_REASSEMBLY_AUTH42 = 0x8ad,
  HEADER_CC_REPLAYPACKET = 0x8ae,
  HEADER_HC_WAITING_LOGIN = 0x8af,
  HEADER_CH_WAITING_LOGIN = 0x8b0,
  HEADER_ZC_MCSTORE_NOTMOVEITEM_LIST = 0x8b1,
  HEADER_AC_REALNAME_AUTH = 0x8b2,
  HEADER_ZC_SHOWSCRIPT = 0x8b3,
  HEADER_ZC_START_COLLECTION = 0x8b4,
  HEADER_CZ_TRYCOLLECTION = 0x8b5,
  HEADER_ZC_TRYCOLLECTION = 0x8b6,
  HEADER_HC_SECOND_PASSWD_REQ = 0x8b7,
  HEADER_CH_SECOND_PASSWD_ACK = 0x8b8,
  HEADER_HC_SECOND_PASSWD_LOGIN = 0x8b9,
  HEADER_CH_MAKE_SECOND_PASSWD = 0x8ba,
  HEADER_HC_MAKE_SECOND_PASSWD = 0x8bb,
  HEADER_CH_DELETE_SECOND_PASSWD = 0x8bc,
  HEADER_HC_DELETE_SECOND_PASSWD = 0x8bd,
  HEADER_CH_EDIT_SECOND_PASSWD = 0x8be,
  HEADER_HC_EDIT_SECOND_PASSWD = 0x8bf,
  HEADER_ZC_ACK_SE_CASH_ITEM_LIST2 = 0x8c0,
  HEADER_CZ_MACRO_START = 0x8c1,
  HEADER_CZ_MACRO_STOP = 0x8c2,
  HEADER_CH_NOT_AVAILABLE_SECOND_PASSWD = 0x8c3,
  HEADER_HC_NOT_AVAILABLE_SECOND_PASSWD = 0x8c4,
  HEADER_CH_AVAILABLE_SECOND_PASSWD = 0x8c5,
  HEADER_HC_AVAILABLE_SECOND_PASSWD = 0x8c6,
  HEADER_ZC_SKILL_ENTRY3 = 0x8c7,
  HEADER_ZC_NOTIFY_ACT3 = 0x8c8,
  HEADER_CZ_REQ_SCHEDULER_CASHITEM = 0x8c9,
  HEADER_ZC_ACK_SCHEDULER_CASHITEM = 0x8ca,
  HEADER_ZC_PERSONAL_INFOMATION = 0x8cb,
  HEADER_CA_LOGIN5 = 0x8cc,
  HEADER_ZC_STOPMOVE_FORCE = 0x8cd,
  HEADER_ZC_FAILED_GET_ITEM_FROM_ZONEDA = 0x8ce,
  HEADER_ZC_SPIRITS_ATTRIBUTE = 0x8cf,
  HEADER_ZC_REQ_WEAR_EQUIP_ACK2 = 0x8d0,
  HEADER_ZC_REQ_TAKEOFF_EQUIP_ACK2 = 0x8d1,
  HEADER_ZC_FASTMOVE = 0x8d2,
  HEADER_ZC_SE_CASHSHOP_UPDATE = 0x8d3,
  HEADER_CH_REQ_CHANGE_CHARACTER_SLOT = 0x8d4,
  HEADER_HC_ACK_CHANGE_CHARACTER_SLOT = 0x8d5,
  HEADER_ZC_CLEAR_DIALOG = 0x8d6,
  HEADER_CZ_REQ_ENTRY_QUEUE_APPLY = 0x8d7,
  HEADER_ZC_ACK_ENTRY_QUEUE_APPLY = 0x8d8,
  HEADER_ZC_NOTIFY_ENTRY_QUEUE_APPLY = 0x8d9,
  HEADER_CZ_REQ_ENTRY_QUEUE_CANCEL = 0x8da,
  HEADER_ZC_ACK_ENTRY_QUEUE_CANCEL = 0x8db,
  HEADER_ZC_NOTIFY_ENTRY_QUEUE_ADMISSION = 0x8dc,
  HEADER_CZ_REPLY_ENTRY_QUEUE_ADMISSION = 0x8dd,
  HEADER_ZC_REPLY_ACK_ENTRY_QUEUE_ADMISSION = 0x8de,
  HEADER_ZC_NOTIFY_LOBBY_ADMISSION = 0x8df,
  HEADER_CZ_REPLY_LOBBY_ADMISSION = 0x8e0,
  HEADER_ZC_REPLY_ACK_LOBBY_ADMISSION = 0x8e1,
  HEADER_ZC_NAVIGATION_ACTIVE = 0x8e2,
  HEADER_HC_UPDATE_CHARINFO = 0x8e3,
  HEADER_AC_SHUTDOWN_INFO = 0x8e4,
  HEADER_CZ_PARTY_RECRUIT_REQ_REGISTER = 0x8e5,
  HEADER_ZC_PARTY_RECRUIT_ACK_REGISTER = 0x8e6,
  HEADER_CZ_PARTY_RECRUIT_REQ_SEARCH = 0x8e7,
  HEADER_ZC_PARTY_RECRUIT_ACK_SEARCH = 0x8e8,
  HEADER_CZ_PARTY_RECRUIT_REQ_DELETE = 0x8e9,
  HEADER_ZC_PARTY_RECRUIT_ACK_DELETE = 0x8ea,
  HEADER_CZ_PARTY_RECRUIT_REQ_UPDATE = 0x8eb,
  HEADER_ZC_PARTY_RECRUIT_NOTIFY_INSERT = 0x8ec,
  HEADER_ZC_PARTY_RECRUIT_NOTIFY_UPDATE = 0x8ed,
  HEADER_ZC_PARTY_RECRUIT_NOTIFY_DELETE = 0x8ee,
  HEADER_CZ_PARTY_RECRUIT_ADD_FILTERLINGLIST = 0x8ef,
  HEADER_CZ_PARTY_RECRUIT_SUB_FILTERLINGLIST = 0x8f0,
  HEADER_CZ_PARTY_RECRUIT_REQ_VOLUNTEER = 0x8f1,
  HEADER_ZC_PARTY_RECRUIT_VOLUNTEER_INFO = 0x8f2,
  HEADER_ZC_PARTY_RECRUIT_PERSONAL_SETTING = 0x8f3,
  HEADER_CZ_PARTY_RECRUIT_SHOW_EQUIPMENT = 0x8f4,
  HEADER_CZ_PARTY_RECRUIT_REQ_RECALL = 0x8f5,
  HEADER_ZC_PARTY_RECRUIT_RECALL_COST = 0x8f6,
  HEADER_CZ_PARTY_RECRUIT_ACK_RECALL = 0x8f7,
  HEADER_ZC_PARTY_RECRUIT_FAILED_RECALL = 0x8f8,
  HEADER_CZ_PARTY_RECRUIT_REFUSE_VOLUNTEER = 0x8f9,
  HEADER_ZC_PARTY_RECRUIT_REFUSE_VOLUNTEER = 0x8fa,
  HEADER_CZ_PARTY_RECRUIT_CANCEL_VOLUNTEER = 0x8fb,
  HEADER_CH_REQ_CHANGE_CHARACTERNAME = 0x8fc,
  HEADER_CH_ACK_CHANGE_CHARACTERNAME = 0x8fd,
  HEADER_ZC_HUNTING_QUEST_INFO = 0x8fe,
  HEADER_ZC_EFST_SET_ENTER = 0x8ff,
  HEADER_ZC_INVENTORY_ITEMLIST_NORMAL = 0x900,
  HEADER_ZC_INVENTORY_ITEMLIST_EQUIP = 0x901,
  HEADER_ZC_CART_ITEMLIST_NORMAL = 0x902,
  HEADER_ZC_CART_ITEMLIST_EQUIP = 0x903,
  HEADER_ZC_STORE_ITEMLIST_NORMAL = 0x904,
  HEADER_ZC_STORE_ITEMLIST_EQUIP = 0x905,
  HEADER_ZC_MICROSCOPE = 0x906,
  HEADER_CZ_INVENTORY_TAB = 0x907,
  HEADER_ZC_INVENTORY_TAB = 0x908,
  HEADER_ZC_PARTY_RECRUIT_CANCEL_VOLUNTEER = 0x909,
  HEADER_CZ_REQ_ENTRY_QUEUE_RANKING = 0x90a,
  HEADER_ZC_PARTY_RECRUIT_ADD_FILTERLINGLIST = 0x90b,
  HEADER_ZC_PARTY_RECRUIT_SUB_FILTERLINGLIST = 0x90c,
  HEADER_ZC_PREMIUM_CAMPAIGN_INFO = 0x90d,
  HEADER_ZC_ENTRY_QUEUE_INIT = 0x90e,
  HEADER_ZC_NOTIFY_NEWENTRY7 = 0x90f,
  HEADER_CZ_REQ_PARTY_NAME = 0x910,
  HEADER_ZC_ACK_PARTY_NAME = 0x911,
  HEADER_CZ_REQ_GUILD_NAME = 0x912,
  HEADER_ZC_ACK_GUILD_NAME = 0x913,
  HEADER_ZC_NOTIFY_MOVEENTRY9 = 0x914,
  HEADER_ZC_NOTIFY_STANDENTRY8 = 0x915,
  HEADER_CZ_REQ_JOIN_GUILD2 = 0x916,
  HEADER_ZC_REASSEMBLY_AUTH43 = 0x917,
  HEADER_ZC_REASSEMBLY_AUTH44 = 0x918,
  HEADER_ZC_REASSEMBLY_AUTH45 = 0x919,
  HEADER_ZC_REASSEMBLY_AUTH46 = 0x91a,
  HEADER_ZC_REASSEMBLY_AUTH47 = 0x91b,
  HEADER_ZC_REASSEMBLY_AUTH48 = 0x91c,
  HEADER_ZC_REASSEMBLY_AUTH49 = 0x91d,
  HEADER_ZC_REASSEMBLY_AUTH50 = 0x91e,
  HEADER_ZC_REASSEMBLY_AUTH51 = 0x91f,
  HEADER_ZC_REASSEMBLY_AUTH52 = 0x920,
  HEADER_ZC_REASSEMBLY_AUTH53 = 0x921,
  HEADER_ZC_REASSEMBLY_AUTH54 = 0x922,
  HEADER_ZC_REASSEMBLY_AUTH55 = 0x923,
  HEADER_ZC_REASSEMBLY_AUTH56 = 0x924,
  HEADER_ZC_REASSEMBLY_AUTH57 = 0x925,
  HEADER_ZC_REASSEMBLY_AUTH58 = 0x926,
  HEADER_ZC_REASSEMBLY_AUTH59 = 0x927,
  HEADER_ZC_REASSEMBLY_AUTH60 = 0x928,
  HEADER_ZC_REASSEMBLY_AUTH61 = 0x929,
  HEADER_ZC_REASSEMBLY_AUTH62 = 0x92a,
  HEADER_ZC_REASSEMBLY_AUTH63 = 0x92b,
  HEADER_ZC_REASSEMBLY_AUTH64 = 0x92c,
  HEADER_ZC_REASSEMBLY_AUTH65 = 0x92d,
  HEADER_ZC_REASSEMBLY_AUTH66 = 0x92e,
  HEADER_ZC_REASSEMBLY_AUTH67 = 0x92f,
  HEADER_ZC_REASSEMBLY_AUTH68 = 0x930,
  HEADER_ZC_REASSEMBLY_AUTH69 = 0x931,
  HEADER_ZC_REASSEMBLY_AUTH70 = 0x932,
  HEADER_ZC_REASSEMBLY_AUTH71 = 0x933,
  HEADER_ZC_REASSEMBLY_AUTH72 = 0x934,
  HEADER_ZC_REASSEMBLY_AUTH73 = 0x935,
  HEADER_ZC_REASSEMBLY_AUTH74 = 0x936,
  HEADER_ZC_REASSEMBLY_AUTH75 = 0x937,
  HEADER_ZC_REASSEMBLY_AUTH76 = 0x938,
  HEADER_ZC_REASSEMBLY_AUTH77 = 0x939,
  HEADER_ZC_REASSEMBLY_AUTH78 = 0x93a,
  HEADER_ZC_REASSEMBLY_AUTH79 = 0x93b,
  HEADER_ZC_REASSEMBLY_AUTH80 = 0x93c,
  HEADER_ZC_REASSEMBLY_AUTH81 = 0x93d,
  HEADER_ZC_REASSEMBLY_AUTH82 = 0x93e,
  HEADER_ZC_REASSEMBLY_AUTH83 = 0x93f,
  HEADER_ZC_REASSEMBLY_AUTH84 = 0x940,
  HEADER_CZ_REASSEMBLY_AUTH43 = 0x941,
  HEADER_CZ_REASSEMBLY_AUTH44 = 0x942,
  HEADER_CZ_REASSEMBLY_AUTH45 = 0x943,
  HEADER_CZ_REASSEMBLY_AUTH46 = 0x944,
  HEADER_CZ_REASSEMBLY_AUTH47 = 0x945,
  HEADER_CZ_REASSEMBLY_AUTH48 = 0x946,
  HEADER_CZ_REASSEMBLY_AUTH49 = 0x947,
  HEADER_CZ_REASSEMBLY_AUTH50 = 0x948,
  HEADER_CZ_REASSEMBLY_AUTH51 = 0x949,
  HEADER_CZ_REASSEMBLY_AUTH52 = 0x94a,
  HEADER_CZ_REASSEMBLY_AUTH53 = 0x94b,
  HEADER_CZ_REASSEMBLY_AUTH54 = 0x94c,
  HEADER_CZ_REASSEMBLY_AUTH55 = 0x94d,
  HEADER_CZ_REASSEMBLY_AUTH56 = 0x94e,
  HEADER_CZ_REASSEMBLY_AUTH57 = 0x94f,
  HEADER_CZ_REASSEMBLY_AUTH58 = 0x950,
  HEADER_CZ_REASSEMBLY_AUTH59 = 0x951,
  HEADER_CZ_REASSEMBLY_AUTH60 = 0x952,
  HEADER_CZ_REASSEMBLY_AUTH61 = 0x953,
  HEADER_CZ_REASSEMBLY_AUTH62 = 0x954,
  HEADER_CZ_REASSEMBLY_AUTH63 = 0x955,
  HEADER_CZ_REASSEMBLY_AUTH64 = 0x956,
  HEADER_CZ_REASSEMBLY_AUTH65 = 0x957,
  HEADER_CZ_REASSEMBLY_AUTH66 = 0x958,
  HEADER_CZ_REASSEMBLY_AUTH67 = 0x959,
  HEADER_CZ_REASSEMBLY_AUTH68 = 0x95a,
  HEADER_CZ_REASSEMBLY_AUTH69 = 0x95b,
  HEADER_CZ_REASSEMBLY_AUTH70 = 0x95c,
  HEADER_CZ_REASSEMBLY_AUTH71 = 0x95d,
  HEADER_CZ_REASSEMBLY_AUTH72 = 0x95e,
  HEADER_CZ_REASSEMBLY_AUTH73 = 0x95f,
  HEADER_CZ_REASSEMBLY_AUTH74 = 0x960,
  HEADER_CZ_REASSEMBLY_AUTH75 = 0x961,
  HEADER_CZ_REASSEMBLY_AUTH76 = 0x962,
  HEADER_CZ_REASSEMBLY_AUTH77 = 0x963,
  HEADER_CZ_REASSEMBLY_AUTH78 = 0x964,
  HEADER_CZ_REASSEMBLY_AUTH79 = 0x965,
  HEADER_CZ_REASSEMBLY_AUTH80 = 0x966,
  HEADER_CZ_REASSEMBLY_AUTH81 = 0x967,
  HEADER_CZ_REASSEMBLY_AUTH82 = 0x968,
  HEADER_CZ_REASSEMBLY_AUTH83 = 0x969,
  HEADER_CZ_REASSEMBLY_AUTH84 = 0x96a,
  HEADER_ZC_PRNPC_STATE = 0x96b,
  HEADER_ZC_PARTY_RECRUIT_CANCEL_VOLUNTEER_TO_PM = 0x96c,
  HEADER_ZC_MERGE_ITEM_OPEN = 0x96d,
  HEADER_CZ_REQ_MERGE_ITEM = 0x96e,
  HEADER_ZC_ACK_MERGE_ITEM = 0x96f,
  HEADER_CH_MAKE_CHAR_NOT_STATS = 0x970,
  HEADER_ZC_PARTY_RECRUIT_REFUSE_VOLUNTEER_TO_PM = 0x971,
  HEADER_ZC_SAY_DIALOG2 = 0x972,
  HEADER_ZC_WAIT_DIALOG2 = 0x973,
  HEADER_CZ_CANCEL_MERGE_ITEM = 0x974,
  HEADER_ZC_STORE_ITEMLIST_NORMAL_V2 = 0x975,
  HEADER_ZC_STORE_ITEMLIST_EQUIP_V2 = 0x976,
  HEADER_ZC_HP_INFO = 0x977,
  HEADER_CZ_REQ_BEFORE_WORLD_INFO = 0x978,
  HEADER_ZC_ACK_BEFORE_WORLD_INFO = 0x979,
  HEADER_ZC_ALL_QUEST_LIST2 = 0x97a,
  HEADER_ZC_PERSONAL_INFOMATION2 = 0x97b,
  HEADER_CZ_REQ_RANKING = 0x97c,
  HEADER_ZC_ACK_RANKING = 0x97d,
  HEADER_ZC_UPDATE_RANKING_POINT = 0x97e,
  HEADER_ZC_SELECTCART = 0x97f,
  HEADER_CZ_SELECTCART = 0x980,
  HEADER_ZC_PERSONAL_INFOMATION_CHN = 0x981,
  HEADER_ZC_FATIGUE_CHN = 0x982,
  HEADER_ZC_MSG_STATE_CHANGE3 = 0x983,
  HEADER_ZC_EFST_SET_ENTER2 = 0x984,
  HEADER_ZC_SKILL_POSTDELAY_LIST2 = 0x985,
  HEADER_AC_SHUTDOWN_NOTIFY = 0x986,
  HEADER_CA_LOGIN_CHN = 0x987,
  HEADER_ZC_NOTIFY_CLAN_CONNECTINFO = 0x988,
  HEADER_ZC_ACK_CLAN_LEAVE = 0x989,
  HEADER_ZC_CLANINFO = 0x98a,
  HEADER_AC_REQ_NEW_USER = 0x98b,
  HEADER_CA_ACK_NEW_USER = 0x98c,
  HEADER_CZ_CLAN_CHAT = 0x98d,
  HEADER_ZC_NOTIFY_CLAN_CHAT = 0x98e,
  HEADER_CH_DELETE_CHAR3_EXT = 0x98f,
  HEADER_ZC_ITEM_PICKUP_ACK_V5 = 0x990,
  HEADER_ZC_INVENTORY_ITEMLIST_NORMAL_V5 = 0x991,
  HEADER_ZC_INVENTORY_ITEMLIST_EQUIP_V5 = 0x992,
  HEADER_ZC_CART_ITEMLIST_NORMAL_V5 = 0x993,
  HEADER_ZC_CART_ITEMLIST_EQUIP_V5 = 0x994,
  HEADER_ZC_STORE_ITEMLIST_NORMAL_V5 = 0x995,
  HEADER_ZC_STORE_ITEMLIST_EQUIP_V5 = 0x996,
  HEADER_ZC_EQUIPWIN_MICROSCOPE_V5 = 0x997,
  HEADER_CZ_REQ_WEAR_EQUIP_V5 = 0x998,
  HEADER_ZC_ACK_WEAR_EQUIP_V5 = 0x999,
  HEADER_ZC_ACK_TAKEOFF_EQUIP_V5 = 0x99a,
  HEADER_ZC_MAPPROPERTY_R2 = 0x99b,
  HEADER_CH_REQ_CHARINFO_PER_PAGE = 0x99c,
  HEADER_HC_ACK_CHARINFO_PER_PAGE = 0x99d,
  HEADER_HC_WAITING_ENTER_QUEUE = 0x99e,
  HEADER_ZC_SKILL_ENTRY4 = 0x99f,
  HEADER_HC_CHARLIST_NOTIFY = 0x9a0,
  HEADER_CH_CHARLIST_REQ = 0x9a1,
  // HEADER_LAST =  0x9a2,
  // for release_2014 this is so but..
  HEADER_AC_REQ_MOBILE_OTP = 0x9a2,
  HEADER_CA_ACK_MOBILE_OTP = 0x9a3,
  HEADER_ZC_DISPATCH_TIMING_INFO_CHN = 0x9a4,
  HEADER_AC_REFUSE_LOGIN3 = 0x9a5,
  HEADER_ZC_BANKING_CHECK = 0x9a6,
  HEADER_CZ_REQ_BANKING_DEPOSIT = 0x9a7,
  HEADER_ZC_ACK_BANKING_DEPOSIT = 0x9a8,
  HEADER_CZ_REQ_BANKING_WITHDRAW = 0x9a9,
  HEADER_ZC_ACK_BANKING_WITHDRAW = 0x9aa,
  HEADER_CZ_REQ_BANKING_CHECK = 0x9ab,
  HEADER_CZ_REQ_CASH_BARGAIN_SALE_ITEM_INFO = 0x9ac,
  HEADER_ZC_ACK_CASH_BARGAIN_SALE_ITEM_INFO = 0x9ad,
  HEADER_CZ_REQ_APPLY_BARGAIN_SALE_ITEM = 0x9ae,
  HEADER_ZC_ACK_APPLY_BARGAIN_SALE_ITEM = 0x9af,
  HEADER_CZ_REQ_REMOVE_BARGAIN_SALE_ITEM = 0x9b0,
  HEADER_ZC_ACK_REMOVE_BARGAIN_SALE_ITEM = 0x9b1,
  HEADER_ZC_NOTIFY_BARGAIN_SALE_SELLING = 0x9b2,
  HEADER_ZC_NOTIFY_BARGAIN_SALE_CLOSE = 0x9b3,
  HEADER_CZ_OPEN_BARGAIN_SALE_TOOL = 0x9b4,
  HEADER_ZC_OPEN_BARGAIN_SALE_TOOL = 0x9b5,
  HEADER_CZ_REQ_OPEN_BANKING = 0x9b6,
  HEADER_ZC_ACK_OPEN_BANKING = 0x9b7,
  HEADER_CZ_REQ_CLOSE_BANKING = 0x9b8,
  HEADER_ZC_ACK_CLOSE_BANKING = 0x9b9,
  XXXXXX_HEADER_CZ_REQ_OPEN_GUILD_STORAGE = 0x9ba,
  HEADER_ZC_ACK_OPEN_GUILD_STORAGE = 0x9bb,
  HEADER_CZ_CLOSE_BARGAIN_SALE_TOOL = 0x9bc,
  HEADER_ZC_CLOSE_BARGAIN_SALE_TOOL = 0x9bd,
  HEADER_CZ_REQ_CLOSE_GUILD_STORAGE = 0x9be,
  HEADER_ZC_ACK_CLOSE_GUILD_STORAGE = 0x9bf,
  HEADER_ZC_ACTION_MOVE = 0x9c0,
  HEADER_ZC_C_MARKERINFO = 0x9c1,
  HEADER_HC_SECRETSCAN_DATA = 0x9c2,
  HEADER_CZ_REQ_COUNT_BARGAIN_SALE_ITEM = 0x9c3,
  HEADER_ZC_ACK_COUNT_BARGAIN_SALE_ITEM = 0x9c4,
  HEADER_CS_LOGIN_QUERY = 0x9c5,
  HEADER_SC_LOGIN_ANSWER = 0x9c6,
  HEADER_SC_LOGIN_ERROR = 0x9c7,
  HEADER_CA_LOGIN_OTP = 0x9c8,
  HEADER_SC_SOCT = 0x9c9,
  HEADER_ZC_SKILL_ENTRY5 = 0x9ca,
  HEADER_ZC_USE_SKILL2 = 0x9cb,
  HEADER_ZC_SECRETSCAN_DATA = 0x9cc,
  HEADER_ZC_MSG_COLOR = 0x9cd,
  HEADER_CZ_ITEM_CREATE_EX = 0x9ce,
  HEADER_ZC_NPROTECTGAMEGUARDCSAUTH = 0x9cf,
  HEADER_CZ_NPROTECTGAMEGUARDCSAUTH = 0x9d0,
  HEADER_ZC_PROGRESS_ACTOR = 0x9d1,
  HEADER_ZC_GUILDSTORAGE_ITEMLIST_NORMAL_V5 = 0x9d2,
  HEADER_ZC_GUILDSTORAGE_ITEMLIST_EQUIP_V5 = 0x9d3,
  HEADER_CZ_NPC_TRADE_QUIT = 0x9d4,
  HEADER_ZC_NPC_MARKET_OPEN = 0x9d5,
  HEADER_CZ_NPC_MARKET_PURCHASE = 0x9d6,
  HEADER_ZC_NPC_MARKET_PURCHASE_RESULT = 0x9d7,
  HEADER_CZ_NPC_MARKET_CLOSE = 0x9d8,
  XXXXXX_HEADER_CZ_REQ_GUILDSTORAGE_LOG = 0x9d9,
  HEADER_ZC_ACK_GUILDSTORAGE_LOG = 0x9da,
  HEADER_ZC_NOTIFY_MOVEENTRY10 = 0x9db,
  HEADER_ZC_NOTIFY_NEWENTRY10 = 0x9dc,
  HEADER_ZC_NOTIFY_STANDENTRY10 = 0x9dd,
  HEADER_ZC_WHISPER02 = 0x9de,
  HEADER_ZC_ACK_WHISPER02 = 0x9df,
  HEADER_SC_LOGIN_ANSWER_WITH_ID = 0x9e0,
  HEADER_CZ_MOVE_ITEM_FROM_BODY_TO_GUILDSTORAGE = 0x9e1,
  HEADER_CZ_MOVE_ITEM_FROM_GUILDSTORAGE_TO_BODY = 0x9e2,
  HEADER_CZ_MOVE_ITEM_FROM_CART_TO_GUILDSTORAGE = 0x9e3,
  HEADER_CZ_MOVE_ITEM_FROM_GUILDSTORAGE_TO_CART = 0x9e4,
  HEADER_ZC_DELETEITEM_FROM_MCSTORE2 = 0x9e5,
  HEADER_ZC_UPDATE_ITEM_FROM_BUYING_STORE2 = 0x9e6,
  HEADER_ZC_NOTIFY_UNREAD_RODEX = 0x9e7,
  HEADER_CZ_OPEN_RODEXBOX = 0x9e8,
  HEADER_CZ_CLOSE_RODEXBOX = 0x9e9,
  HEADER_CZ_REQ_READ_RODEX = 0x9ea,
  HEADER_ZC_ACK_READ_RODEX = 0x9eb,
  HEADER_CZ_REQ_SEND_RODEX = 0x9ec,
  HEADER_ZC_ACK_SEND_RODEX = 0x9ed,
  HEADER_CZ_REQ_NEXT_RODEX = 0x9ee,
  HEADER_CZ_REQ_REFRESH_RODEX = 0x9ef,
  HEADER_ZC_ACK_RODEX_LIST = 0x9f0,
  HEADER_CZ_REQ_ZENY_FROM_RODEX = 0x9f1,
  HEADER_ZC_ACK_ZENY_FROM_RODEX = 0x9f2,
  HEADER_CZ_REQ_ITEM_FROM_RODEX = 0x9f3,
  HEADER_ZC_ACK_ITEM_FROM_RODEX = 0x9f4,
  HEADER_CZ_REQ_DELETE_RODEX = 0x9f5,
  HEADER_ZC_ACK_DELETE_RODEX = 0x9f6,
  HEADER_ZC_PROPERTY_HOMUN_2 = 0x9f7,
  HEADER_ZC_ALL_QUEST_LIST3 = 0x9f8,
  HEADER_ZC_ADD_QUEST_EX = 0x9f9,
  HEADER_ZC_UPDATE_MISSION_HUNT_EX = 0x9fa,
  HEADER_CZ_PET_EVOLUTION = 0x9fb,
  HEADER_ZC_PET_EVOLUTION_RESULT = 0x9fc,
  HEADER_ZC_NOTIFY_MOVEENTRY11 = 0x9fd,
  HEADER_ZC_NOTIFY_NEWENTRY11 = 0x9fe,
  HEADER_ZC_NOTIFY_STANDENTRY11 = 0x9ff,
  HEADER_ZC_SHORTCUT_KEY_LIST_V3 = 0xa00,
  HEADER_CZ_SHORTCUTKEYBAR_ROTATE = 0xa01,
  HEADER_ZC_DRESSROOM_OPEN = 0xa02,
  HEADER_CZ_REQ_CANCEL_WRITE_RODEX = 0xa03,
  HEADER_CZ_REQ_ADD_ITEM_RODEX = 0xa04,
  HEADER_ZC_ACK_ADD_ITEM_RODEX = 0xa05,
  HEADER_CZ_REQ_REMOVE_RODEX_ITEM = 0xa06,
  HEADER_ZC_ACK_REMOVE_RODEX_ITEM = 0xa07,
  HEADER_CZ_REQ_OPEN_WRITE_RODEX = 0xa08,
  HEADER_ZC_ADD_EXCHANGE_ITEM3 = 0xa09,
  HEADER_ZC_ADD_ITEM_TO_STORE3 = 0xa0a,
  HEADER_ZC_ADD_ITEM_TO_CART3 = 0xa0b,
  HEADER_ZC_ITEM_PICKUP_ACK_V6 = 0xa0c,
  HEADER_ZC_INVENTORY_ITEMLIST_EQUIP_V6 = 0xa0d,
  HEADER_ZC_BATTLEFIELD_NOTIFY_HP2 = 0xa0e,
  HEADER_ZC_CART_ITEMLIST_EQUIP_V6 = 0xa0f,
  HEADER_ZC_STORE_ITEMLIST_EQUIP_V6 = 0xa10,
  HEADER_ZC_GUILDSTORAGE_ITEMLIST_EQUIP_V6 = 0xa11,
  HEADER_ZC_ACK_OPEN_WRITE_RODEX = 0xa12,
  HEADER_CZ_CHECK_RECEIVE_CHARACTER_NAME = 0xa13,
  HEADER_ZC_CHECK_RECEIVE_CHARACTER_NAME = 0xa14,
  HEADER_ZC_GOLDPCCAFE_POINT = 0xa15,
  HEADER_CZ_DYNAMICNPC_CREATE_REQUEST = 0xa16,
  HEADER_ZC_DYNAMICNPC_CREATE_RESULT = 0xa17,
  HEADER_ZC_ACCEPT_ENTER3 = 0xa18,
  HEADER_CZ_REQ_OPEN_ROULETTE = 0xa19,
  HEADER_ZC_ACK_OPEN_ROULETTE = 0xa1a,
  HEADER_CZ_REQ_ROULETTE_INFO = 0xa1b,
  HEADER_ZC_ACK_ROULEITTE_INFO = 0xa1c,
  HEADER_CZ_REQ_CLOSE_ROULETTE = 0xa1d,
  HEADER_ZC_ACK_CLOSE_ROULETTE = 0xa1e,
  HEADER_CZ_REQ_GENERATE_ROULETTE = 0xa1f,
  HEADER_ZC_ACK_GENERATE_ROULETTE = 0xa20,
  HEADER_CZ_RECV_ROULETTE_ITEM = 0xa21,
  HEADER_ZC_RECV_ROULETTE_ITEM = 0xa22,
  HEADER_ZC_ALL_ACH_LIST = 0xa23,
  HEADER_ZC_ACH_UPDATE = 0xa24,
  HEADER_CZ_REQ_ACH_REWARD = 0xa25,
  HEADER_ZC_REQ_ACH_REWARD_ACK = 0xa26,
  HEADER_ZC_RECOVERY2 = 0xa27,
  HEADER_ZC_ACK_OPENSTORE2 = 0xa28,
  HEADER_ZC_REQ_AU_BOT = 0xa29,
  HEADER_CZ_ACK_AU_BOT = 0xa2a,
  HEADER_ZC_SE_CASHSHOP_OPEN2 = 0xa2b,
  HEADER_ZC_SE_PC_BUY_TAIWANCASHITEM_RESULT = 0xa2c,
  HEADER_ZC_EQUIPWIN_MICROSCOPE_V6 = 0xa2d,
  HEADER_CZ_REQ_CHANGE_TITLE = 0xa2e,
  HEADER_ZC_ACK_CHANGE_TITLE = 0xa2f,
  HEADER_ZC_ACK_REQNAMEALL2 = 0xa30,
  HEADER_ZC_RESULT_PACKAGE_ITEM_TEST = 0xa31,
  HEADER_ZC_OPEN_RODEX_THROUGH_NPC_ONLY = 0xa32,
  HEADER_ZC_UPDATE_ROULETTE_COIN = 0xa33,
  HEADER_ZC_UPDATE_TAIWANCASH = 0xa34,
  HEADER_CZ_REQ_ONECLICK_ITEMIDENTIFY = 0xa35,
  HEADER_ZC_HP_INFO_TINY = 0xa36,
  HEADER_ZC_ITEM_PICKUP_ACK_V7 = 0xa37,
  HEADER_LAST = 0xa38,

  HEADER_CUSTOM_START = 0xD00,
  HEADER_CUSTOM_CZ_NOTIFY_CLIENTMODIFICATION = 0xd00,
  HEADER_CUSTOM_CA_MACCHECK = 0xd01,
  HEADER_CUSTOM_CA_DOMDLL_HASHCHECK = 0xd02

};

// Packet Structures
#pragma pack(push)
#pragma pack(1)
#pragma warning(disable : 4200)

struct CHAR_SERVER_INFO {
  uint32_t ip_address;
  uint16_t port;
  char name[20];
  uint16_t user_count;
  uint16_t state;
  uint16_t property_;
};

struct PACKET_CA_LOGIN {
  uint16_t header;
  uint32_t version;
  char username[24];
  char password[24];
  uint8_t client_type;
};

struct PACKET_CH_ENTER {
  uint16_t header;
  uint32_t account_id;
  int32_t auth_code;
  uint32_t user_level;
  uint16_t client_type;
  uint8_t Sex;
};

struct PACKET_CH_SELECT_CHAR {
  uint16_t header;
  uint8_t char_num;
};

struct PACKET_CH_MAKE_CHAR {
  uint16_t header;
  char name[24];
  uint8_t str;
  uint8_t agi;
  uint8_t vit;
  uint8_t int_;
  uint8_t dex;
  uint8_t luk;
  uint8_t char_slot;
  uint16_t head_color;
  uint16_t head_style;
};

struct PACKET_CH_DELETE_CHAR {
  uint16_t header;
  uint32_t char_id;
  char email[40];
};

struct PACKET_AC_ACCEPT_LOGIN {
  uint16_t header;
  uint16_t packet_len;
  int32_t auth_code;
  uint32_t account_id;
  uint32_t user_level;
  uint32_t lastlogin_ip;
  char lastlogin_time[26];
  uint8_t sex;
  CHAR_SERVER_INFO server_info[0];
};

struct PACKET_AC_REFUSE_LOGIN {
  uint16_t header;
  uint8_t error_code;
  char block_date[20];
};

struct PACKET_HC_ACCEPT_ENTER {
  uint16_t header;
  uint16_t packet_len;
#if PACKETVER >= 20100413
  uint8_t total_slots;
  uint8_t premium_slots_start;
  uint8_t premium_slots_end;
#endif
  uint8_t unknown[20];
  CharacterInfo charinfo[];
};

struct PACKET_HC_REFUSE_ENTER {
  uint16_t header;
  uint8_t error_code;
};

struct PACKET_HC_ACCEPT_MAKECHAR {
  uint16_t header;
  CharacterInfo charinfo;
};

struct PACKET_HC_REFUSE_MAKECHAR {
  uint16_t header;
  uint8_t error_code;
};

struct PACKET_HC_ACCEPT_DELETECHAR {
  uint16_t header;
};

struct PACKET_HC_REFUSE_DELETECHAR {
  uint16_t header;
  uint8_t error_code;
};

struct PACKET_SC_NOTIFY_BAN {
  uint16_t header;
  uint8_t error_code;
};

struct PACKET_CA_REQ_HASH {
  uint16_t header;
};

struct PACKET_AC_ACK_HASH {
  uint16_t header;
  uint16_t packet_len;
  uint8_t salt[];
};

struct PACKET_PING {
  uint16_t header;
  uint32_t account_id;
};

struct PACKET_CA_LOGIN2 {
  uint16_t header;
  uint32_t version;
  char username[24];
  uint8_t password_md5[16];
  uint8_t client_type;
};

struct PACKET_CA_LOGIN3 {
  uint16_t header;
  uint32_t version;
  char username[24];
  uint8_t password_md5[16];
  uint8_t client_type;
  uint8_t client_info;
};

struct PACKET_CH_DELETE_CHAR2 {
  uint16_t header;
  uint32_t char_id;
  char email[50];
};

struct PACKET_CA_LOGIN_PCBANG {
  uint16_t header;
  uint32_t version;
  char username[24];
  char password[24];
  uint8_t clienttype;
  char ip_address[16];
  char mac_address[13];
};

struct PACKET_CA_REQ_GAME_GUARD_CHECK {
  uint16_t header;
};

struct PACKET_AC_ACK_GAME_GUARD {
  uint16_t header;
  uint8_t answer;
};

struct PACKET_CA_LOGIN4 {
  uint16_t header;
  uint32_t version;
  char username[24];
  uint8_t password_md5[16];
  uint8_t clienttype;
  char mac_address[13];
};

struct PACKET_CA_LOGIN_CHANNEL {
  uint16_t header;
  uint32_t version;
  char username[24];
  char password[24];
  uint8_t clienttype;
  char ip_address[16];
  char mac_address[13];
  uint8_t channeling_corp;
};

struct PACKET_CA_LOGIN_TOKEN {
  uint16_t header;
  uint16_t packet_len;
  uint32_t version;
  uint8_t client_type;
  char username[24];
  char password[27];
  char mac_address[17];
  char ip_address[15];
  char access_token[];
};

struct PACKET_CH_ENTER_CHECKBOT {
  uint16_t header;
  uint16_t packet_len;
  uint32_t account_id;
};

struct PACKET_CH_CHECKBOT {
  uint16_t header;
  uint16_t packet_len;
  uint32_t account_id;
  char szStringInfo[24];
};

struct PACKET_HC_CHECKBOT {
  uint16_t header;
  uint16_t packet_len;
};

struct PACKET_HC_CHECKBOT_RESULT {
  uint16_t header;
  uint16_t packet_len;
  uint8_t result;
};

struct PACKET_ZC_REFUSE_ENTER {
  uint16_t header;
  uint8_t error;
};

struct PACKET_ZC_MSG_SKILL {
  uint16_t header;
  uint16_t SKID;
  int32_t MSGID;
};

struct PACKET_CZ_BATTLE_FIELD_LIST {
  uint16_t header;
};

struct PACKET_ZC_BATTLE_FIELD_LIST {
  uint16_t header;
  uint16_t packet_length;
  int16_t Count;
};

struct PACKET_CZ_JOIN_BATTLE_FIELD {
  uint16_t header;
  uint32_t BFNO;
  int16_t JoinTeam;
};

struct PACKET_ZC_JOIN_BATTLE_FIELD {
  uint16_t header;
  uint32_t BFNO;
  int16_t JoinTeam;
  int16_t Result;
};

struct PACKET_CZ_CANCEL_BATTLE_FIELD {
  uint16_t header;
  uint32_t BFNO;
};

struct PACKET_ZC_CANCEL_BATTLE_FIELD {
  uint16_t header;
  uint32_t BFNO;
  int16_t Result;
};

struct PACKET_CZ_REQ_BATTLE_STATE_MONITOR {
  uint16_t header;
  uint32_t BFNO;
};

struct PACKET_ZC_ACK_BATTLE_STATE_MONITOR {
  uint16_t header;
  char BFNO;
  int16_t PlayCount;
  int16_t BattleState;
  int16_t TeamCount_A;
  int16_t TeamCount_B;
  int16_t MyCount;
  int16_t JoinTeam;
};

struct PACKET_ZC_BATTLE_NOTI_START_STEP {
  uint16_t header;
  int16_t BFNO;
  int16_t Result;
};

struct PACKET_ZC_BATTLE_JOIN_NOTI_DEFER {
  uint16_t header;
  int16_t BFNO;
};

struct PACKET_ZC_BATTLE_JOIN_DISABLE_STATE {
  uint16_t header;
  bool Enable;
};

struct PACKET_CZ_GM_FULLSTRIP {
  uint16_t header;
  uint32_t TargetAID;
};

struct PACKET_ZC_NOTIFY_EXP {
  uint16_t header;
  uint32_t AID;
  int32_t amount;
  uint16_t varID;
  int16_t expType;
};

struct PACKET_ZC_NOTIFY_MOVEENTRY7 {
  uint16_t header;
  uint16_t packet_length;
  uint8_t objecttype;
  uint32_t GID;
  int16_t speed;
  int16_t bodyState;
  int16_t healthState;
  int32_t effectState;
  int16_t job;
  int16_t head;
  int32_t weapon;
  int16_t accessory;
  uint32_t moveStartTime;
  int16_t accessory2;
  int16_t accessory3;
  int16_t headpalette;
  int16_t bodypalette;
  int16_t headDir;
  uint32_t GUID;
  int16_t GEmblemVer;
  int16_t honor;  // PK Mode?
  int32_t virtue;
  bool isPKModeON;
  uint8_t sex;
  uint8_t MoveData[6];
  uint8_t xSize;
  uint8_t ySize;
  int16_t clevel;
  int16_t font;
};

// Old Packet? Not used btw.
struct PACKET_ZC_NOTIFY_NEWENTRY5 {
  uint16_t header;
  uint16_t packet_length;
  uint8_t objecttype;
  uint32_t GID;
  int16_t speed;
  int16_t bodyState;
  int16_t healthState;
  int32_t effectState;
  int16_t job;
  int16_t head;
  int32_t weapon;
  int16_t accessory;
  int16_t accessory2;
  int16_t accessory3;
  int16_t headpalette;
  int16_t bodypalette;
  int16_t headDir;
  uint32_t GUID;
  int16_t GEmblemVer;
  int16_t honor;
  int32_t virtue;
  bool isPKModeON;
  uint8_t sex;
  uint8_t PosDir[3];
  uint8_t xSize;
  uint8_t ySize;
  int16_t clevel;
  int16_t font;
};

// Another one? Y U DO THIS?
struct PACKET_ZC_NOTIFY_STANDENTRY5 {
  uint16_t header;
  uint16_t packet_length;
  uint8_t objecttype;
  uint32_t GID;
  int16_t speed;
  int16_t bodyState;
  int16_t healthState;
  int32_t effectState;
  int16_t job;
  int16_t head;
  int32_t weapon;
  int16_t accessory;
  int16_t accessory2;
  int16_t accessory3;
  int16_t headpalette;
  int16_t bodypalette;
  int16_t headDir;
  uint32_t GUID;
  int16_t GEmblemVer;
  int16_t honor;
  int32_t virtue;
  bool isPKModeON;
  uint8_t sex;
  uint8_t PosDir[3];
  uint8_t xSize;
  uint8_t ySize;
  uint8_t state;
  int16_t clevel;
  int16_t font;
};

struct PACKET_ZC_DELETE_ITEM_FROM_BODY {
  uint16_t header;
  int16_t DeleteType;
  uint16_t Index;
  int16_t Count;
};

struct PACKET_ZC_USESKILL_ACK2 {
  uint16_t header;
  uint32_t AID;
  uint32_t targetID;
  int16_t xPos;
  int16_t yPos;
  uint16_t SKID;
  uint32_t property;
  uint32_t delayTime;
  bool isDisposable;
};

struct PACKET_ZC_CHANGE_GROUP_MASTER {
  uint16_t header;
  uint32_t OldMasterAID;
  uint32_t NewMasterAID;
};

struct PACKET_ZC_BROADCASTING_SPECIAL_ITEM_OBTAIN {
  uint16_t header;
  uint16_t packet_length;
  uint8_t type;
  uint16_t ItemID;
};

struct PACKET_ZC_PLAY_NPC_BGM {
  uint16_t header;
  char Bgm[24];
};

/* Useless Packet. SKIP ALLLLL THE USELESS PACKETS
struct PACKET_ZC_DEFINE_CHECK {
int16_t header;
int16_t PacketLength;
};*/

struct PACKET_ZC_PC_PURCHASE_ITEMLIST_FROMMC2 {
  uint16_t header;
  uint16_t packet_length;
  uint32_t AID;
  uint32_t UniqueID;
};

struct PACKET_CZ_PC_PURCHASE_ITEMLIST_FROMMC2 {
  uint16_t header;
  uint16_t packet_length;
  uint32_t AID;
  uint32_t UniqueID;
};

struct PACKET_CZ_PARTY_BOOKING_REQ_REGISTER {
  uint16_t header;

  struct PARTY_BOOKING_DETAIL {
    int16_t Level;
    int16_t MapID;
    int16_t Job[6];
  } RegisterInfo;
};

struct PACKET_ZC_PARTY_BOOKING_ACK_REGISTER {
  uint16_t header;
  int16_t Result;
};

struct PACKET_CZ_PARTY_BOOKING_REQ_SEARCH {
  uint16_t header;
  int16_t Level;
  int16_t MapID;
  int16_t Job;
  uint32_t LastIndex;
  int16_t ResultCount;
};

struct PACKET_ZC_PARTY_BOOKING_ACK_SEARCH {
  uint16_t header;
  uint16_t packet_length;
  bool IsExistMoreResult;
};

struct PACKET_CZ_PARTY_BOOKING_REQ_DELETE {
  uint16_t header;
};

struct PACKET_ZC_PARTY_BOOKING_ACK_DELETE {
  uint16_t header;
  int16_t Result;
};

struct PACKET_CZ_PARTY_BOOKING_REQ_UPDATE {
  uint16_t header;
  int16_t Job[6];
};

struct PACKET_ZC_PARTY_BOOKING_NOTIFY_INSERT {
  uint16_t header;

  struct PARTY_BOOKING_AD_INFO {
    uint32_t Index;
    char CharName[24];
    int32_t ExpireTime;

    struct PARTY_BOOKING_DETAIL {
      int16_t Level;
      int16_t MapID;
      int16_t Job[6];
    } detail;
  } info;
};

struct PACKET_ZC_PARTY_BOOKING_NOTIFY_UPDATE {
  uint16_t header;
  uint32_t Index;
  int16_t Job[6];
};

struct PACKET_ZC_PARTY_BOOKING_NOTIFY_DELETE {
  uint16_t header;
  uint32_t Index;
};

struct PACKET_CZ_SIMPLE_CASH_BTNSHOW {
  uint16_t header;
};

struct PACKET_ZC_SIMPLE_CASH_BTNSHOW {
  uint16_t header;
  bool show;
};

struct PACKET_ZC_NOTIFY_HP_TO_GROUPM_R2 {
  uint16_t header;
  uint32_t AID;
  int32_t hp;
  int32_t maxhp;
};

struct PACKET_ZC_ADD_EXCHANGE_ITEM2 {
  uint16_t header;
  uint16_t ITID;
  uint8_t type;
  int32_t count;
  bool IsIdentified;
  bool IsDamaged;
  uint8_t refiningLevel;
  struct EQUIPSLOTINFO {
    uint16_t info[4];
  } slot;
};

struct PACKET_ZC_OPEN_BUYING_STORE {
  uint16_t header;
  uint8_t count;
};

struct PACKET_CZ_REQ_OPEN_BUYING_STORE {
  uint16_t header;
  uint16_t packet_length;
  uint32_t LimitZeny;
  uint8_t result;
  char storeName[80];
};

struct PACKET_ZC_FAILED_OPEN_BUYING_STORE_TO_BUYER {
  uint16_t header;
  int16_t Result;
  int32_t total_weight;
};

struct PACKET_ZC_MYITEMLIST_BUYING_STORE {
  uint16_t header;
  uint16_t packet_length;
  uint32_t AID;
  int32_t limitZeny;
};

struct PACKET_ZC_BUYING_STORE_ENTRY {
  uint16_t header;
  uint32_t makerAID;
  char storeName[80];
};

struct PACKET_CZ_REQ_CLOSE_BUYING_STORE {
  uint16_t header;
};

struct PACKET_ZC_DISAPPEAR_BUYING_STORE_ENTRY {
  uint16_t header;
  uint32_t makerAID;
};

struct PACKET_CZ_REQ_CLICK_TO_BUYING_STORE {
  uint16_t header;
  uint32_t makerAID;
};

struct PACKET_ZC_ACK_ITEMLIST_BUYING_STORE {
  uint16_t header;
  uint16_t packet_length;
  uint32_t makerAID;
  uint32_t StoreID;
  int32_t limitZeny;
};

struct PACKET_CZ_REQ_TRADE_BUYING_STORE {
  uint16_t header;
  uint16_t packet_length;
  uint32_t makerAID;
  uint32_t StoreID;
};

struct PACKET_ZC_FAILED_TRADE_BUYING_STORE_TO_BUYER {
  uint16_t header;
  int16_t Result;
};

struct PACKET_ZC_UPDATE_ITEM_FROM_BUYING_STORE {
  uint16_t header;
  uint16_t ITID;
  int16_t count;
  int32_t limitZeny;
};

struct PACKET_ZC_ITEM_DELETE_BUYING_STORE {
  uint16_t header;
  int16_t index;
  int16_t count;
  int32_t zeny;
};

struct PACKET_ZC_EL_INIT {
  uint16_t header;
  int32_t AID;
  int32_t hp;
  int32_t maxHP;
  int32_t sp;
  int32_t maxSP;
};

struct PACKET_ZC_EL_PAR_CHANGE {
  uint16_t header;
  uint16_t var;
  int32_t value;
};

struct PACKET_ZC_BROADCAST_IN_ZONE {
  uint16_t header;
  uint16_t packet_length;
  uint8_t Msgtype;
  uint32_t ColorRGB;
};

struct PACKET_ZC_COSTUME_SPRITE_CHANGE {
  uint16_t header;
  uint32_t GID;
  uint8_t type;
  int32_t value;
};

struct PACKET_AC_OTP_USER {
  uint16_t header;
};

struct PACKET_CA_OTP_AUTH_REQ {
  uint16_t header;
  char OTPCode[7];
};

struct PACKET_AC_OTP_AUTH_ACK {
  uint16_t header;
  uint16_t packet_length;
  uint16_t LoginResult;
};

struct PACKET_ZC_FAILED_TRADE_BUYING_STORE_TO_SELLER {
  uint16_t header;
  int16_t Result;
  uint16_t ITID;
};

struct PACKET_HC_NOTIFY_ZONESVR {
  uint16_t header;
  uint32_t char_id;
  uint8_t map_name[16];
  struct ZSERVER_ADDR {
    uint32_t ip;
    int16_t port;
  } addr;
};

struct PACKET_CZ_REQUEST_CHAT {
  uint16_t header;
  uint16_t packet_length;
  char msg[];
};

struct PACKET_ZC_NOTIFY_CHAT {
  uint16_t header;
  uint16_t packet_length;
  uint32_t GID;
};

struct PACKET_ZC_NOTIFY_PLAYERCHAT {
  uint16_t header;
  uint16_t packet_length;
  char msg[];
};

struct PACKET_ZC_AID {
  uint16_t header;
  uint32_t AID;
};

struct PACKET_ZC_NOTIFY_TIME {
  uint16_t header;
  uint32_t time;
};

struct PACKET_ZC_ACCEPT_ENTER {
  uint16_t header;
  uint32_t startTime;
  uint8_t PosDir[3];
  uint8_t xSize;
  uint8_t ySize;
};

struct PACKET_ZC_ACCEPT_ENTER2 {
  uint16_t header;
  uint32_t startTime;
  uint8_t PosDir[3];
  uint8_t xSize;
  uint8_t ySize;
  uint16_t font;
};

struct PACKET_ZC_NPC_CHAT {
  uint16_t header;
  uint16_t packet_length;
  uint32_t accountID;
  uint32_t color;
  char msg;
};

struct PACKET_CA_CONNECT_INFO_CHANGE {
  uint16_t header;
  char ID[24];
};

struct PACKET_CZ_ENTER {
  uint16_t header;
  // char pad[0x2];
  uint32_t AID;
  // char pad2[0x1];
  uint32_t GID;
  // char pad3[0x4];
  uint32_t AuthCode;
  uint32_t clientTime;
  char Sex;
};

struct PACKET_CZ_ENTER2 {
  uint16_t header;
  uint32_t aid;
  uint32_t gid;
  int32_t auth_code;
  uint32_t client_time;
  uint8_t sex;
};

struct PACKET_ZC_NPCACK_MAPMOVE {
  uint16_t header;
  char map_name[16];
  int16_t x_pos;
  int16_t y_pos;
};

struct PACKET_ZC_COUPLESTATUS {
  uint16_t header;
  uint32_t status_type;
  int32_t default_status;
  int32_t plus_status;
};

struct PACKET_ZC_PAR_CHANGE {
  uint16_t header;
  uint16_t var_id;
  int32_t count;
};

struct PACKET_CZ_USE_ITEM {
  uint16_t header;
  uint16_t index;
  uint32_t AID;
};

struct PACKET_ZC_ATTACK_RANGE {
  uint16_t header;
  int16_t current_att_range;
};

struct PACKET_HC_BLOCK_CHARACTER {
  uint16_t header;
  uint16_t packet_length;
  struct TAG_CHARACTER_BLOCK_INFO {
    uint32_t GID;
    char szExpireDate[20];
  } charList[];
};

struct PACKET_ZC_CLOSE_DIALOG {
  uint16_t header;
  uint32_t naid;
};

struct PACKET_CZ_REQUEST_TIME {
  uint16_t header;
  uint32_t client_time;
};

struct PACKET_CZ_NOTIFY_ACTORINIT {
  uint16_t header;
};

struct PACKET_ZC_SPRITE_CHANGE2 {
  uint16_t header;
  uint32_t gid;
  uint8_t type;
  int32_t value;
};

struct PACKET_ZC_EQUIPMENT_ITEMLIST3 {
  uint16_t header;
  int16_t packet_length;
  struct EQUIPMENTITEM_EXTRAINFO301 {
    int16_t index;
    uint16_t itid;
    uint8_t type;
    bool is_identified;
    uint16_t location;
    uint8_t wear_state;
    bool is_damaged;
    uint8_t refining_level;
    struct EQUIPSLOTINFO {
      uint16_t card1;
      uint16_t card2;
      uint16_t card3;
      uint16_t card4;
    } slot;
    int32_t hire_expire_date;
    uint16_t bind_on_equip_type;
    uint16_t w_item_sprite_number;
  } ItemInfo[];
};

struct PACKET_ZC_NOTIFY_MAPPROPERTY {
  uint16_t header;
  int16_t type;
};

struct PACKET_ZC_NOTIFY_STANDENTRY {
  uint16_t header;
  uint8_t object_type;
  uint32_t gid;
  int16_t speed;
  int16_t body_state;
  int16_t health_state;
  int16_t effect_state;
  int16_t job;
  int16_t head;
  int16_t weapon;
  int16_t accessory;
  int16_t shield;
  int16_t accessory2;
  int16_t accessory3;
  int16_t head_palette;
  int16_t body_palette;
  int16_t head_dir;
  uint32_t guid;
  int16_t g_emblem_ver;
  int16_t honor;
  int16_t virtue;
  bool is_pk_mode_on;
  uint8_t sex;
  uint8_t pos_dir[3];
  uint8_t x_size;
  uint8_t y_size;
  uint8_t state;
  int16_t clevel;
};

struct PACKET_ZC_SKILLINFO_LIST {
  uint16_t header;
  uint16_t packet_length;
  struct SKILLINFO {
    int16_t skill_id;
    int32_t type;
    int16_t level;
    int16_t sp_cost;
    int16_t attack_range;
    uint8_t skill_name[24];
    int8_t upgradable;
  } skillList[];
};

struct PACKET_ZC_SHORTCUT_KEY_LIST {
  uint16_t header;
  struct ShortCutKey {
    int8_t is_skill;
    uint32_t id;
    int16_t count;
  } shortcut_keys[27];
};

struct PACKET_ZC_LONGPAR_CHANGE {
  uint16_t header;
  uint16_t var_id;
  int32_t amount;
};

struct PACKET_ZC_STATUS {
  uint16_t header;
  int16_t point;
  uint8_t str;
  uint8_t standard_str;
  uint8_t agi;
  uint8_t standard_agi;
  uint8_t vit;
  uint8_t standard_vit;
  uint8_t Int;
  uint8_t standard_int;
  uint8_t dex;
  uint8_t standard_dex;
  uint8_t luk;
  uint8_t standard_luk;
  int16_t att_power;
  int16_t refining_power;
  int16_t max_matt_power;
  int16_t min_matt_power;
  int16_t itemdef_power;
  int16_t plusdef_power;
  int16_t mdef_power;
  int16_t plusmdef_power;
  int16_t hit_success_value;
  int16_t avoid_success_value;
  int16_t plus_avoid_success_value;
  int16_t critical_success_value;
  int16_t aspd;
  int16_t plus_aspd;
};

struct PACKET_ZC_PARTY_CONFIG {
  uint16_t header;
  bool refuse_join_msg;
};

struct PACKET_ZC_CONFIG_NOTIFY {
  uint16_t header;
  bool open_equipment_win;
};

struct PACKET_ZC_BROADCAST2 {
  uint16_t header;
  uint16_t packet_length;
  uint32_t font_color;
  int16_t font_type;
  int16_t font_size;
  int16_t font_align;
  int16_t font_y;
  char msg[];
};

struct PACKET_ZC_EMOTION {
  uint16_t header;
  uint32_t gid;
  uint8_t type;
};

#pragma pack(pop)
#pragma warning(default : 4200)

#endif  // DOLORI_NETWORK_PACKETS_H_
